-- ANAGROCI FBMS - AFLP Farmer Registry Phase 1
-- Deterministic ordering of consent and private identity-document events.
-- Applied to Supabase on 2026-08-18 as farmer_registry_phase1_06_event_ordering.

begin;

alter table public.farmer_consents
  add column if not exists event_order bigint generated by default as identity;
alter table public.farmer_identity_documents
  add column if not exists event_order bigint generated by default as identity;

alter table public.farmer_consents alter column created_at set default clock_timestamp();
alter table public.farmer_identity_documents alter column created_at set default clock_timestamp();

create index if not exists farmer_consents_producteur_event_idx
  on public.farmer_consents (producteur_id, event_order desc);
create index if not exists farmer_identity_documents_producteur_event_idx
  on public.farmer_identity_documents (producteur_id, event_order desc);

create or replace function public.farmer_registry_prepare_consent()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  previous_id uuid;
begin
  if new.consent_at > now() + interval '1 day' then
    raise exception 'Date de consentement future interdite.';
  end if;
  if nullif(btrim(new.text_version),'') is null then
    raise exception 'Version du texte de consentement obligatoire.';
  end if;
  if jsonb_typeof(new.scopes) is distinct from 'object' then
    raise exception 'Perimetres de consentement invalides.';
  end if;
  if new.status = 'GRANTED' and not (
    coalesce((new.scopes->>'identity')::boolean, false)
    and coalesce((new.scopes->>'agriculture')::boolean, false)
    and coalesce((new.scopes->>'gps')::boolean, false)
    and coalesce((new.scopes->>'photos')::boolean, false)
    and coalesce((new.scopes->>'training')::boolean, false)
    and coalesce((new.scopes->>'inspections')::boolean, false)
    and coalesce((new.scopes->>'transactions')::boolean, false)
  ) then
    raise exception 'Un consentement GRANTED exige tous les perimetres.';
  end if;
  if new.status = 'PARTIAL' and not (
    coalesce((new.scopes->>'identity')::boolean, false)
    or coalesce((new.scopes->>'agriculture')::boolean, false)
    or coalesce((new.scopes->>'gps')::boolean, false)
    or coalesce((new.scopes->>'photos')::boolean, false)
    or coalesce((new.scopes->>'training')::boolean, false)
    or coalesce((new.scopes->>'inspections')::boolean, false)
    or coalesce((new.scopes->>'transactions')::boolean, false)
  ) then
    raise exception 'Un consentement PARTIAL exige au moins un perimetre.';
  end if;

  if new.supersedes_id is null then
    select c.id into previous_id
    from public.farmer_consents c
    where c.producteur_id = new.producteur_id
    order by c.event_order desc
    limit 1;
    new.supersedes_id := previous_id;
  end if;

  new.agent_id := coalesce(new.agent_id, auth.uid());
  new.created_by := coalesce(new.created_by, auth.uid());
  return new;
exception
  when invalid_text_representation then
    raise exception 'Perimetres de consentement invalides.';
end
$$;

create or replace function public.farmer_registry_prepare_identity_document()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  previous_id uuid;
begin
  if new.supersedes_id is null then
    select d.id into previous_id
    from public.farmer_identity_documents d
    where d.producteur_id = new.producteur_id
      and d.status = 'ACTIVE'
    order by d.event_order desc
    limit 1;
    new.supersedes_id := previous_id;
  else
    previous_id := new.supersedes_id;
  end if;

  if previous_id is not null then
    update public.farmer_identity_documents
    set status = case when new.status = 'WITHDRAWN' then 'WITHDRAWN' else 'REPLACED' end
    where id = previous_id and status = 'ACTIVE';
  end if;

  new.created_by := coalesce(new.created_by, auth.uid());
  return new;
end
$$;

create or replace function public.farmer_registry_refresh_passport(p_producteur_id text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  p public.producteurs%rowtype;
  c public.farmer_consents%rowtype;
  identity_points integer := 0;
  assignment_points integer := 0;
  consent_points integer := 0;
  total_points integer := 0;
  stage_value text := 'INCOMPLETE';
  risk_value text := 'NOT_ASSESSED';
  consent_status_value text := 'NOT_RECORDED';
begin
  select * into p from public.producteurs where id = p_producteur_id;
  if p.id is null then return; end if;

  select * into c
  from public.farmer_consents
  where producteur_id = p_producteur_id
  order by event_order desc
  limit 1;

  if nullif(btrim(p.nom),'') is not null
     and p.sexe is not null
     and (p.birth_year is not null or nullif(btrim(p.age_band),'') is not null)
     and length(public.farmer_registry_norm_phone(p.telephone)) = 10
  then identity_points := 30; end if;

  if p.village_id is not null and p.rt_id is not null then
    assignment_points := 20;
  end if;

  if c.id is not null then
    consent_status_value := c.status;
    if c.status = 'GRANTED' then consent_points := 15;
    elsif c.status = 'PARTIAL' then consent_points := 8;
    end if;
  end if;

  total_points := identity_points + assignment_points + consent_points;
  if identity_points = 30 and assignment_points = 20 and consent_status_value = 'GRANTED' then
    stage_value := 'BASIC';
  end if;
  if p.review_required
     or p.possible_duplicate
     or consent_status_value in ('PARTIAL','REFUSED','WITHDRAWN') then
    risk_value := 'REVIEW_REQUIRED';
  end if;

  update public.producteurs
  set
    passport_completion = total_points,
    passport_stage = stage_value,
    risk_profile = risk_value,
    consent_status = consent_status_value,
    consent_date = case when c.id is null then null else c.consent_at end,
    consent_version = case when c.id is null then null else c.text_version end,
    consent_method = case when c.id is null then null else c.method end
  where id = p_producteur_id
    and (
      passport_completion is distinct from total_points
      or passport_stage is distinct from stage_value
      or risk_profile is distinct from risk_value
      or consent_status is distinct from consent_status_value
      or consent_date is distinct from case when c.id is null then null else c.consent_at end
      or consent_version is distinct from case when c.id is null then null else c.text_version end
      or consent_method is distinct from case when c.id is null then null else c.method end
    );
end
$$;

revoke all on function public.farmer_registry_prepare_consent() from public, anon, authenticated;
revoke all on function public.farmer_registry_prepare_identity_document() from public, anon, authenticated;
revoke all on function public.farmer_registry_refresh_passport(text) from public, anon, authenticated;

commit;
