begin;

-- AFLP Sustainability operational catalog v2026.2.
-- Keep 2026.1 for historical readability; new baselines/inspections use 2026.2.
insert into public.sustainability_question_catalog
(question_code,catalog_version,domain,sequence_no,label_fr,label_en,guidance_fr,required,risk_trigger_answers,risk_level,default_corrective_action,default_priority,active)
values
('A01','AFLP-SUST-2026.2','AGRICULTURAL_PRACTICES',1,'La parcelle est-elle suffisamment entretenue pour permettre l’accès, le suivi et la récolte ?','Is the plot sufficiently maintained for access, monitoring and harvest?','Observer l’enherbement excessif, l’accès aux arbres et l’état général. Un couvert végétal maîtrisé n’est pas une anomalie.',true,array['NO','PARTIAL']::text[],'MEDIUM','Planifier les travaux d’entretien nécessaires sans mettre inutilement le sol à nu.','MEDIUM',true),
('A02','AFLP-SUST-2026.2','AGRICULTURAL_PRACTICES',2,'Une taille sanitaire ou d’entretien est-elle pratiquée lorsque le verger en a besoin ?','Is sanitary or maintenance pruning carried out when the orchard needs it?','Rechercher les traces de taille et vérifier la compréhension de la pratique. Répondre NON APPLICABLE si le jeune verger n’en a pas encore besoin.',true,array['NO','PARTIAL']::text[],'MEDIUM','Former le producteur à la taille utile et programmer une démonstration pratique.','MEDIUM',true),
('A03','AFLP-SUST-2026.2','AGRICULTURAL_PRACTICES',3,'Les branches mortes, arbres malades ou foyers visibles de ravageurs sont-ils repérés et gérés ?','Are dead branches, diseased trees or visible pest hotspots identified and managed?','Observer les arbres concernés et demander ce que fait le producteur lorsqu’un problème apparaît.',true,array['NO','PARTIAL']::text[],'MEDIUM','Identifier les foyers concernés et appliquer une méthode de gestion adaptée avec l’appui technique AFLP.','MEDIUM',true),
('A04','AFLP-SUST-2026.2','AGRICULTURAL_PRACTICES',4,'La zone sous les arbres est-elle préparée pour une récolte propre et sûre ?','Is the area under the trees prepared for a clean and safe harvest?','Vérifier que les noix peuvent être ramassées sans obstacle majeur, tout en évitant un décapage excessif du sol.',true,array['NO','PARTIAL']::text[],'MEDIUM','Préparer la zone de récolte avant campagne en conservant une protection suffisante du sol.','MEDIUM',true),
('A05','AFLP-SUST-2026.2','AGRICULTURAL_PRACTICES',5,'Les noix récoltées sont-elles séchées et conservées à l’abri de l’humidité avant la vente ?','Are harvested nuts dried and kept away from moisture before sale?','Vérifier le séchage, l’ensachage, le contact avec le sol et le lieu de stockage temporaire.',true,array['NO','PARTIAL']::text[],'MEDIUM','Améliorer le séchage et le stockage temporaire afin de protéger la qualité des noix.','MEDIUM',true),
('A06','AFLP-SUST-2026.2','AGRICULTURAL_PRACTICES',6,'Les arbres morts ou durablement improductifs sont-ils remplacés progressivement lorsque cela est nécessaire ?','Are dead or persistently unproductive trees progressively replaced when needed?','Évaluer seulement lorsque le renouvellement est pertinent. Répondre NON APPLICABLE si aucun besoin n’est identifié.',true,array['NO','PARTIAL']::text[],'MEDIUM','Préparer un plan simple de renouvellement des arbres morts ou improductifs.','LOW',true),
('B01','AFLP-SUST-2026.2','ENVIRONMENT',7,'Existe-t-il des preuves récentes de brûlage non contrôlé dans ou autour de la parcelle ?','Is there recent evidence of uncontrolled burning in or around the plot?','Observer les traces de feu et demander les circonstances. Ne pas confondre un feu maîtrisé autorisé avec un brûlage incontrôlé.',true,array['YES']::text[],'HIGH','Arrêter le brûlage non contrôlé, sensibiliser le producteur et mettre en place des mesures de prévention.','HIGH',true),
('B02','AFLP-SUST-2026.2','ENVIRONMENT',8,'Lorsque le risque de feu existe, une mesure de prévention fonctionnelle est-elle en place ?','Where fire risk exists, is an effective prevention measure in place?','Vérifier pare-feu, débroussaillement raisonné, surveillance ou autre mesure locale pertinente. Répondre NON APPLICABLE si le risque est absent.',true,array['NO','PARTIAL']::text[],'HIGH','Mettre en place ou réhabiliter une mesure de prévention du feu adaptée au site avant la période à risque.','HIGH',true),
('B03','AFLP-SUST-2026.2','ENVIRONMENT',9,'Observe-t-on une érosion importante du sol sur la parcelle ?','Is significant soil erosion visible on the plot?','Rechercher ravines, ruissellement marqué, perte de terre ou racines fortement mises à nu.',true,array['YES']::text[],'HIGH','Mettre en place des mesures antiérosives adaptées aux zones concernées.','HIGH',true),
('B04','AFLP-SUST-2026.2','ENVIRONMENT',10,'Au moins une pratique adaptée de protection du sol est-elle utilisée lorsque nécessaire ?','Is at least one suitable soil-protection practice used where needed?','Exemples : couverture végétale maîtrisée, paillage, bandes enherbées, courbes de niveau ou autre pratique adaptée.',true,array['NO','PARTIAL']::text[],'MEDIUM','Introduire une pratique simple de protection du sol adaptée à la parcelle et en suivre l’application.','MEDIUM',true),
('B05','AFLP-SUST-2026.2','ENVIRONMENT',11,'Le producteur applique-t-il des pratiques qui limitent les risques pour les pollinisateurs ?','Does the farmer apply practices that reduce risks to pollinators?','Vérifier notamment la période de floraison, les horaires de traitement, la présence d’abeilles et les pratiques de pulvérisation. NON APPLICABLE si aucun pesticide n’est utilisé.',true,array['NO','PARTIAL']::text[],'MEDIUM','Former le producteur aux pratiques de protection des pollinisateurs et adapter le calendrier de traitement.','MEDIUM',true),
('B06','AFLP-SUST-2026.2','ENVIRONMENT',12,'La parcelle empiète-t-elle visiblement sur une forêt naturelle, une aire protégée ou une zone humide sensible ?','Does the plot visibly encroach on natural forest, a protected area or a sensitive wetland?','Utiliser les observations terrain et le GPS disponibles. En cas de doute sérieux, choisir INCONNU ou NON VÉRIFIÉ pour déclencher une revue, sans conclure automatiquement à une violation.',true,array['YES','UNKNOWN','NOT_VERIFIED']::text[],'REVIEW_REQUIRED','Suspendre toute extension de la parcelle dans la zone sensible et faire vérifier la situation par la supervision avant décision.','CRITICAL',true),
('C01','AFLP-SUST-2026.2','PHYTOSANITARY_MANAGEMENT',13,'Des pesticides ou autres produits phytosanitaires sont-ils utilisés sur cette exploitation ?','Are pesticides or other crop-protection products used on this farm?','Question de contexte. OUI n’est pas automatiquement une non-conformité. Les questions C02 à C07 peuvent être NON APPLICABLE si aucun produit n’est utilisé ou stocké.',true,array[]::text[],'NONE',null,'LOW',true),
('C02','AFLP-SUST-2026.2','PHYTOSANITARY_MANAGEMENT',14,'Lorsque des produits sont utilisés, leur nom et leur usage sont-ils connus et vérifiables ?','Where products are used, are their name and intended use known and verifiable?','Demander le nom du produit ou observer l’étiquette/contenant. NON APPLICABLE si C01 = NON.',true,array['NO','PARTIAL','UNKNOWN','NOT_VERIFIED']::text[],'HIGH','Identifier les produits utilisés et former le producteur à l’usage des produits autorisés ou recommandés.','HIGH',true),
('C03','AFLP-SUST-2026.2','PHYTOSANITARY_MANAGEMENT',15,'Les équipements de protection nécessaires sont-ils disponibles pour la manipulation ou la pulvérisation ?','Is the necessary protective equipment available for handling or spraying?','Vérifier les EPI réellement disponibles. NON APPLICABLE si aucun produit n’est manipulé.',true,array['NO','PARTIAL']::text[],'HIGH','Mettre à disposition les EPI nécessaires avant toute manipulation ou pulvérisation.','HIGH',true),
('C04','AFLP-SUST-2026.2','PHYTOSANITARY_MANAGEMENT',16,'Les équipements de protection sont-ils effectivement portés lors de la manipulation ou pulvérisation ?','Is protective equipment actually worn during handling or spraying?','Distinguer ce qui est déclaré de ce qui est observé. NON APPLICABLE si aucune manipulation ou pulvérisation n’a lieu.',true,array['NO','PARTIAL']::text[],'HIGH','Former les personnes concernées et contrôler l’utilisation effective des EPI.','HIGH',true),
('C05','AFLP-SUST-2026.2','PHYTOSANITARY_MANAGEMENT',17,'Des pulvérisations sont-elles réalisées sur fleurs ouvertes ou en présence d’abeilles sans mesure de protection adaptée ?','Are sprays applied on open flowers or when bees are active without suitable protection measures?','Questionner sur l’horaire, la floraison, le produit utilisé et les mesures prises pour réduire le risque pollinisateurs.',true,array['YES']::text[],'HIGH','Revoir immédiatement le calendrier et les conditions de pulvérisation pendant la floraison.','HIGH',true),
('C06','AFLP-SUST-2026.2','PHYTOSANITARY_MANAGEMENT',18,'Des emballages vides de pesticides sont-ils réutilisés pour l’eau, les aliments ou un autre usage dangereux, ou abandonnés sans précaution ?','Are empty pesticide containers reused for water, food or another unsafe purpose, or discarded unsafely?','Vérifier les usages domestiques, le stockage et l’élimination des contenants. En cas d’impossibilité de vérification malgré un usage de pesticides, choisir NON VÉRIFIÉ.',true,array['YES','UNKNOWN','NOT_VERIFIED']::text[],'REVIEW_REQUIRED','Cesser immédiatement la réutilisation dangereuse et mettre en place une élimination ou collecte sûre des emballages.','CRITICAL',true),
('C07','AFLP-SUST-2026.2','PHYTOSANITARY_MANAGEMENT',19,'Les produits phytosanitaires présents sont-ils stockés dans un endroit fermé, séparé des aliments et inaccessible aux enfants ?','Are crop-protection products stored locked, away from food and inaccessible to children?','Vérifier séparation, fermeture, accès aux enfants et état du lieu. NON APPLICABLE si aucun produit n’est stocké.',true,array['NO','PARTIAL']::text[],'HIGH','Aménager un stockage fermé, séparé et sécurisé pour les produits phytosanitaires.','HIGH',true),
('D01','AFLP-SUST-2026.2','SOCIAL_SAFETY',20,'Existe-t-il un signe qu’un travailleur est empêché de quitter librement son travail, privé de ses papiers, menacé ou lié par une dette ?','Is there any sign that a worker is prevented from leaving freely, has documents withheld, is threatened or is bound by debt?','Question sensible : recueillir des faits sans confrontation. INCONNU ou NON VÉRIFIÉ signifie qu’une revue est nécessaire, pas qu’une violation est prouvée.',true,array['YES','UNKNOWN','NOT_VERIFIED']::text[],'REVIEW_REQUIRED','Protéger immédiatement la personne concernée, préserver la confidentialité et transmettre le cas à la supervision pour revue et remédiation.','CRITICAL',true),
('D02','AFLP-SUST-2026.2','SOCIAL_SAFETY',21,'Des violences, menaces, harcèlement, discrimination ou retenues abusives de salaire ont-ils été signalés par les travailleurs ?','Have workers reported violence, threats, harassment, discrimination or abusive wage withholding?','Questionner avec discrétion. NON APPLICABLE s’il n’existe aucun travailleur autre que le producteur lui-même.',true,array['YES']::text[],'HIGH','Documenter le signalement de façon confidentielle, protéger la personne concernée et faire examiner le cas par la supervision.','HIGH',true),
('D03','AFLP-SUST-2026.2','SOCIAL_SAFETY',22,'Des personnes de moins de 18 ans participent-elles à certaines activités de l’exploitation ?','Do persons under 18 take part in any farm activities?','Question de contexte uniquement. Toute participation d’un mineur n’est pas automatiquement du travail des enfants : préciser l’âge, la tâche, la durée, le danger éventuel et l’impact sur la scolarité.',true,array[]::text[],'NONE',null,'LOW',true),
('D04','AFLP-SUST-2026.2','SOCIAL_SAFETY',23,'Un mineur effectue-t-il une tâche dangereuse ou une activité qui compromet sa santé, sa sécurité ou sa scolarité ?','Does a minor perform hazardous work or work that harms health, safety or schooling?','Inclure produits chimiques, charges lourdes, machines, outils dangereux, hauteur, longues heures et toute activité incompatible avec la scolarité.',true,array['YES','UNKNOWN','NOT_VERIFIED']::text[],'REVIEW_REQUIRED','Retirer immédiatement le mineur des tâches dangereuses et engager une revue de protection et de remédiation.','CRITICAL',true),
('D05','AFLP-SUST-2026.2','SOCIAL_SAFETY',24,'Existe-t-il une exposition chimique non maîtrisée d’un travailleur lors du stockage, mélange, traitement ou lavage ?','Is there uncontrolled worker exposure to chemicals during storage, mixing, spraying or washing?','Évaluer les pratiques réelles, les EPI, les éclaboussures, le lavage du matériel et le contact avec des vêtements contaminés.',true,array['YES','UNKNOWN','NOT_VERIFIED']::text[],'REVIEW_REQUIRED','Stopper l’exposition non maîtrisée, fournir les protections nécessaires et corriger immédiatement la pratique concernée.','CRITICAL',true),
('D06','AFLP-SUST-2026.2','SOCIAL_SAFETY',25,'Un accident ou incident de sécurité significatif a-t-il eu lieu sur l’exploitation au cours des 12 derniers mois ?','Has a significant safety accident or incident occurred on the farm in the last 12 months?','Documenter le fait, sa date, sa gravité, les personnes concernées et les mesures prises depuis.',true,array['YES']::text[],'HIGH','Analyser la cause de l’incident et mettre en œuvre puis vérifier les mesures correctives nécessaires.','HIGH',true)
on conflict (question_code,catalog_version) do update set
 domain=excluded.domain, sequence_no=excluded.sequence_no, label_fr=excluded.label_fr, label_en=excluded.label_en,
 guidance_fr=excluded.guidance_fr, required=excluded.required, risk_trigger_answers=excluded.risk_trigger_answers,
 risk_level=excluded.risk_level, default_corrective_action=excluded.default_corrective_action,
 default_priority=excluded.default_priority, active=excluded.active, updated_at=now();

alter table public.farmer_sustainability_baselines alter column catalog_version set default 'AFLP-SUST-2026.2';
alter table public.farmer_inspections alter column catalog_version set default 'AFLP-SUST-2026.2';

commit;
