-- Replica locale : vues, gardes, flux legacy et RPC ops EXACTS de production (18/09/2026).
create sequence if not exists public.bag_request_seq;
create sequence if not exists public.bag_movement_seq;
create table if not exists public.aflp_bag_envelopes (
  id uuid default gen_random_uuid() not null primary key, campaign text not null, approved_qty integer not null,
  status text default 'GM_APPROVED'::text not null, approved_by uuid, approved_at timestamp with time zone,
  notes text, created_by uuid, created_at timestamp with time zone default now() not null);
create table if not exists public.aflp_bag_cluster_allocations (
  id uuid default gen_random_uuid() not null primary key, envelope_id uuid not null, cluster text not null,
  allocated_qty integer not null, created_by uuid, created_at timestamp with time zone default now() not null);
create table if not exists public.audit_log (
  id bigserial primary key, ts timestamp with time zone default now() not null, email text, action text, details text);
create table if not exists public.rcn_proc_audit_central (
  id bigint generated by default as identity primary key, table_name text not null, record_id text not null,
  action text not null, before_data jsonb, after_data jsonb, actor_id uuid, actor_role text,
  created_at timestamp with time zone default now() not null);

create view public.rcn_jute_v_stock with (security_invoker=true) as  WITH x AS (
         SELECT rcn_jute_movements.to_location AS location_code,
            rcn_jute_movements.to_state AS state,
            rcn_jute_movements.qty AS delta
           FROM rcn_jute_movements
          WHERE ((rcn_jute_movements.ledger = 'INTERNE'::text) AND (rcn_jute_movements.to_location IS NOT NULL) AND (rcn_jute_movements.to_state IS NOT NULL))
        UNION ALL
         SELECT rcn_jute_movements.from_location,
            rcn_jute_movements.from_state,
            (- rcn_jute_movements.qty)
           FROM rcn_jute_movements
          WHERE ((rcn_jute_movements.ledger = 'INTERNE'::text) AND (rcn_jute_movements.from_location IS NOT NULL) AND (rcn_jute_movements.from_state IS NOT NULL))
        )
 SELECT location_code,
    state,
    (sum(delta))::integer AS qty
   FROM x
  GROUP BY location_code, state;
create view public.sacherie_ct_cluster_stock with (security_invoker=true) as  SELECT l.cluster,
    (COALESCE(sum(s.qty) FILTER (WHERE ((l.scope_type = 'CLUSTER'::text) AND (s.state = 'UTILISABLE'::text))), (0)::bigint))::integer AS stock_cluster_vide,
    (COALESCE(sum(s.qty) FILTER (WHERE ((l.scope_type = 'CLUSTER'::text) AND (s.state = 'PLEIN'::text))), (0)::bigint))::integer AS stock_cluster_plein,
    (COALESCE(sum(s.qty) FILTER (WHERE (l.scope_type = 'RT'::text)), (0)::bigint))::integer AS stock_chez_rt,
    (COALESCE(sum(s.qty) FILTER (WHERE (l.scope_type = 'PRODUCTEUR'::text)), (0)::bigint))::integer AS stock_chez_producteur,
    (COALESCE(sum(s.qty) FILTER (WHERE ((l.scope_type = 'HUB'::text) AND (s.state = 'PLEIN'::text))), (0)::bigint))::integer AS stock_hub_plein,
    (COALESCE(sum(s.qty) FILTER (WHERE (s.state = 'DECHIRE'::text)), (0)::bigint))::integer AS dechires,
    (COALESCE(sum(s.qty) FILTER (WHERE (s.state = 'A_REPARER'::text)), (0)::bigint))::integer AS a_reparer,
    (COALESCE(sum(s.qty) FILTER (WHERE (s.state = 'REPARE'::text)), (0)::bigint))::integer AS repares,
    (COALESCE(sum(s.qty) FILTER (WHERE (s.state = 'REFORME'::text)), (0)::bigint))::integer AS rebut,
    (COALESCE(sum(s.qty) FILTER (WHERE (s.state = 'EN_TRANSIT'::text)), (0)::bigint))::integer AS transit,
    (COALESCE(sum(s.qty), (0)::bigint))::integer AS total_reseau
   FROM (rcn_jute_locations l
     LEFT JOIN rcn_jute_v_stock s ON ((s.location_code = l.code)))
  WHERE (l.scope_type = ANY (ARRAY['CLUSTER'::text, 'RT'::text, 'PRODUCTEUR'::text, 'HUB'::text]))
  GROUP BY l.cluster;
create view public.sacherie_ct_latest_inventory with (security_invoker=true) as  SELECT DISTINCT ON (location_code, state) id,
    inventory_batch_id, location_code, state, theoretical_qty, counted_qty, difference_qty, motif, statut,
    reconciliation_status, counted_at, approved_at, proof_url
   FROM rcn_jute_inventories
  ORDER BY location_code, state, counted_at DESC, id DESC;
create view public.sacherie_ct_rt_stock with (security_invoker=true) as  WITH stock AS (
         SELECT l.cluster, l.rt_id, max(l.nom) AS rt_nom,
            (COALESCE(sum(s_1.qty), (0)::bigint))::integer AS total_sous_responsabilite,
            (COALESCE(sum(s_1.qty) FILTER (WHERE (s_1.state = 'UTILISABLE'::text)), (0)::bigint))::integer AS vides,
            (COALESCE(sum(s_1.qty) FILTER (WHERE (s_1.state = 'PLEIN'::text)), (0)::bigint))::integer AS pleins,
            (COALESCE(sum(s_1.qty) FILTER (WHERE (s_1.state = 'DECHIRE'::text)), (0)::bigint))::integer AS dechires,
            (COALESCE(sum(s_1.qty) FILTER (WHERE (s_1.state = 'A_REPARER'::text)), (0)::bigint))::integer AS a_reparer,
            (COALESCE(sum(s_1.qty) FILTER (WHERE (s_1.state = 'REPARE'::text)), (0)::bigint))::integer AS repares,
            (COALESCE(sum(s_1.qty) FILTER (WHERE (s_1.state = 'REFORME'::text)), (0)::bigint))::integer AS rebut
           FROM (rcn_jute_locations l LEFT JOIN rcn_jute_v_stock s_1 ON ((s_1.location_code = l.code)))
          WHERE (l.scope_type = 'RT'::text)
          GROUP BY l.cluster, l.rt_id
        ), activite AS (
         SELECT l.cluster, l.rt_id, max(m.movement_at) AS derniere_activite
           FROM (rcn_jute_locations l LEFT JOIN rcn_jute_movements m ON (((m.from_location = l.code) OR (m.to_location = l.code))))
          WHERE (l.scope_type = 'RT'::text)
          GROUP BY l.cluster, l.rt_id
        )
 SELECT s.cluster, s.rt_id, s.rt_nom, s.total_sous_responsabilite, s.vides, s.pleins, s.dechires, s.a_reparer,
    s.repares, s.rebut, a.derniere_activite
   FROM (stock s LEFT JOIN activite a USING (cluster, rt_id));

CREATE OR REPLACE FUNCTION public.fb_prevent_negative_bag_stock()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare
  k text;
  bal integer := 0;
begin
  if new.source = 'CLUSTER' then
    k := public.fb_entity_key(null, new.cluster);
    select coalesce(sum(case when destination='CLUSTER' then quantite when source='CLUSTER' then -quantite else 0 end),0) into bal
    from public.sacs_mouvements m
    where public.fb_entity_key(null, m.cluster) = k
      and coalesce(m.local_id,'') <> coalesce(new.local_id,'')
      and m.id <> coalesce(new.id, m.id);
  elsif new.source = 'RT' then
    k := public.fb_entity_key(new.rt_id, new.rt_nom);
    select coalesce(sum(case when destination='RT' then quantite when source='RT' then -quantite else 0 end),0) into bal
    from public.sacs_mouvements m
    where public.fb_entity_key(m.rt_id, m.rt_nom) = k
      and coalesce(m.local_id,'') <> coalesce(new.local_id,'')
      and m.id <> coalesce(new.id, m.id);
  elsif new.source = 'PRODUCTEUR' then
    k := public.fb_entity_key(new.producteur_id, new.producteur_nom);
    select coalesce(sum(case when destination='PRODUCTEUR' then quantite when source='PRODUCTEUR' then -quantite else 0 end),0) into bal
    from public.sacs_mouvements m
    where public.fb_entity_key(m.producteur_id, m.producteur_nom) = k
      and coalesce(m.local_id,'') <> coalesce(new.local_id,'')
      and m.id <> coalesce(new.id, m.id);
  else
    return new;
  end if;

  if bal < coalesce(new.quantite,0) then
    raise exception 'Stock sacs insuffisant. Disponible: %, sortie: %', bal, new.quantite
      using errcode = '23514';
  end if;

  return new;
end $function$
;
CREATE OR REPLACE FUNCTION public.ops_bag_request_guard()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
declare v_uid uuid:=auth.uid();
begin
  if v_uid is null then return new; end if;
  if tg_op='INSERT' then
    new.requested_by:=v_uid; new.requested_at:=coalesce(new.requested_at,now()); new.status:='REQUESTED';
    new.approved_qty:=null; new.released_qty:=0; new.received_qty:=0;
    new.reviewed_by:=null; new.reviewed_at:=null; new.approved_by:=null; new.approved_at:=null;
    return new;
  end if;
  if old.channel<>new.channel or old.requested_by<>new.requested_by or old.requested_qty<>new.requested_qty then raise exception 'Identité de la demande non modifiable après création'; end if;
  if old.status is distinct from new.status then
    if new.status in ('REJECTED','CANCELLED') then
      if not private.ops_has_role(array['General Manager','Branch Manager','Procurement Officer','LBA Purchase Officer','Field Buying Operations Officer','Zonal Head']) then raise exception 'Droit insuffisant pour clôturer la demande'; end if;
    elsif old.channel='LBA' and old.status='REQUESTED' and new.status='REVIEWED' then
      if not private.ops_has_role(array['Procurement Officer','LBA Purchase Officer','Branch Manager']) then raise exception 'Review LBA réservé au Procurement'; end if;
      new.reviewed_by:=v_uid; new.reviewed_at:=now();
    elsif old.channel='LBA' and old.status='REVIEWED' and new.status='GM_APPROVED' then
      if not private.ops_has_role(array['General Manager']) then raise exception 'Seul le General Manager peut approuver les sacs LBA'; end if;
      if v_uid=old.requested_by then raise exception 'Séparation des tâches : l’initiateur ne peut pas approuver sa propre demande'; end if;
      if new.approved_qty is null or new.approved_qty<=0 or new.approved_qty>old.requested_qty then raise exception 'Quantité approuvée invalide'; end if;
      new.approved_by:=v_uid; new.approved_at:=now();
    elsif old.channel='AFLP' and old.status='REQUESTED' and new.status='REVIEWED' then
      if not private.ops_has_role(array['Zonal Head','Branch Manager']) then raise exception 'Review AFLP réservé au Zonal Head'; end if;
      new.reviewed_by:=v_uid; new.reviewed_at:=now();
    elsif old.channel='AFLP' and old.status='REVIEWED' and new.status='CONSOLIDATED' then
      if not private.ops_has_role(array['Field Buying Operations Officer','Branch Manager']) then raise exception 'Consolidation AFLP réservée au Field Buying Operations Officer'; end if;
    elsif old.channel='AFLP' and old.status='CONSOLIDATED' and new.status='BM_APPROVED' then
      if not private.ops_has_role(array['Branch Manager']) then raise exception 'Seul le Branch Manager peut approuver Cluster vers RT'; end if;
      if v_uid=old.requested_by then raise exception 'Séparation des tâches : l’initiateur ne peut pas approuver sa propre demande'; end if;
      if new.approved_qty is null or new.approved_qty<=0 or new.approved_qty>old.requested_qty then raise exception 'Quantité approuvée invalide'; end if;
      new.approved_by:=v_uid; new.approved_at:=now();
    elsif new.status in ('PARTIALLY_RELEASED','FULLY_RELEASED') then
      if not private.ops_has_role(array['Warehouse Manager','Storekeeper','Procurement Officer','Branch Manager','Warehouse Keeper','Assistant Unit Head']) then raise exception 'Sortie physique réservée au magasin'; end if;
    elsif new.status='EXPIRED' then
      if new.expires_at is null or new.expires_at>=now() then raise exception 'Approval non expiré'; end if;
    else raise exception 'Transition sacherie non autorisée: % vers %',old.status,new.status;
    end if;
  end if;

  -- AJOUT : confirmation de reception. Traversait le guard sans aucun controle.
  if new.received_qty is distinct from old.received_qty then
    if new.received_qty < old.received_qty then
      raise exception 'Une reception confirmee ne peut pas etre diminuee (% vers %)', old.received_qty, new.received_qty;
    end if;
    if not private.ops_has_role(array['Unit Head','Field Buying Operations Officer','Branch Manager','Administrateur']) then
      raise exception 'Confirmation de reception reservee au terrain destinataire';
    end if;
    if new.received_qty < new.released_qty
       and coalesce(btrim(new.receipt_gap_reason),'') = '' then
      raise exception 'Ecart de reception (% recus sur % liberes) : motif obligatoire', new.received_qty, new.released_qty;
    end if;
  end if;

  new.updated_at:=now(); return new;
end $function$
;
CREATE OR REPLACE FUNCTION public.ops_release_bags(p_request_id uuid, p_client_release_id text, p_source_location text, p_destination_location text, p_qty integer, p_proof_url text DEFAULT NULL::text, p_note text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
declare
  v_uid uuid := auth.uid();
  v_req public.ops_bag_requests%rowtype;
  v_existing public.ops_bag_releases%rowtype;
  v_available integer;
  v_move_id text;
  v_release public.ops_bag_releases%rowtype;
  v_new_total integer;
begin
  if v_uid is null then raise exception 'Connexion requise'; end if;
  if not private.ops_has_role(array['Branch Manager','Warehouse Manager','Storekeeper','Procurement Officer','Warehouse Keeper','Assistant Unit Head']) then
    raise exception 'Droit insuffisant pour libérer les sacs';
  end if;
  if p_client_release_id is null or btrim(p_client_release_id)='' then raise exception 'Idempotency key obligatoire'; end if;
  if p_qty is null or p_qty<=0 then raise exception 'Quantité de sacs invalide'; end if;
  select * into v_existing from public.ops_bag_releases where client_release_id=p_client_release_id limit 1;
  if found then return to_jsonb(v_existing); end if;
  select * into v_req from public.ops_bag_requests where id=p_request_id for update;
  if not found then raise exception 'Demande de sacs introuvable'; end if;
  if v_req.approved_by = v_uid then raise exception 'Séparation des tâches : approbateur et exécutant doivent être différents'; end if;
  if v_req.status not in ('GM_APPROVED','BM_APPROVED','READY_FOR_RELEASE','PARTIALLY_RELEASED') then raise exception 'Approval valide requis avant la sortie physique'; end if;
  if v_req.expires_at is not null and v_req.expires_at < now() then
    update public.ops_bag_requests set status='EXPIRED',updated_at=now() where id=v_req.id;
    raise exception 'Approval expiré';
  end if;
  if p_source_location is distinct from v_req.source_location_code or p_destination_location is distinct from v_req.destination_location_code then
    raise exception 'Source/destination différentes de l’autorisation';
  end if;
  if v_req.approved_qty is null then raise exception 'Quantité approuvée absente'; end if;
  if v_req.released_qty + p_qty > v_req.approved_qty then raise exception 'Sortie supérieure à l’autorisation restante'; end if;
  perform pg_advisory_xact_lock(42070,hashtext(p_source_location));
  select coalesce(sum(qty),0)::integer into v_available from public.rcn_jute_v_stock where location_code=p_source_location and state='UTILISABLE';
  if v_available < p_qty then raise exception 'Stock utilisable insuffisant'; end if;
  v_move_id := 'JUT-OPS-'||replace(gen_random_uuid()::text,'-','');
  insert into public.rcn_jute_movements(id,event_key,movement_type,ledger,supplier_code,qty,from_location,to_location,from_state,to_state,source_type,source_id,reference,note,proof_url,movement_at,created_by,owner_type,campaign,cluster,rt_id)
  values(v_move_id,'OPS-BAG-RELEASE:'||p_client_release_id,'TRANSFERT','INTERNE',v_req.lba_code,p_qty,p_source_location,p_destination_location,'UTILISABLE','UTILISABLE','OPS_BAG_REQUEST',v_req.id::text,v_req.request_code,p_note,p_proof_url,now(),v_uid,'ANAGROCI',v_req.campaign,v_req.cluster,v_req.rt_id);
  insert into public.ops_bag_releases(client_release_id,request_id,qty,source_location_code,destination_location_code,jute_movement_id,released_by,proof_url,notes)
  values(p_client_release_id,v_req.id,p_qty,p_source_location,p_destination_location,v_move_id,v_uid,p_proof_url,p_note)
  returning * into v_release;
  v_new_total:=v_req.released_qty+p_qty;
  update public.ops_bag_requests
     set released_qty=v_new_total,
         status=case when v_new_total < approved_qty then 'PARTIALLY_RELEASED' else 'FULLY_RELEASED' end,
         updated_at=now()
   where id=v_req.id;
  return to_jsonb(v_release);
exception when unique_violation then
  select * into v_existing from public.ops_bag_releases where client_release_id=p_client_release_id limit 1;
  if found then return to_jsonb(v_existing); end if;
  raise;
end
$function$
;
CREATE OR REPLACE FUNCTION private.rcn_jute_guard()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'private'
AS $function$
declare available integer; debt integer;
begin
 if auth.uid() is null then raise exception 'Authentification requise'; end if;
 if new.ledger='INTERNE' and new.from_location is not null and new.from_state is not null then
  select coalesce(sum(case when to_location=new.from_location and to_state=new.from_state then qty else 0 end),0)-coalesce(sum(case when from_location=new.from_location and from_state=new.from_state then qty else 0 end),0)
  into available from public.rcn_jute_movements;
  if available<new.qty then raise exception 'Stock de sacs insuffisant (% disponibles)',available; end if;
 end if;
 if new.ledger='FOURNISSEUR' and new.movement_type in('RETOUR','PERTE_APPROUVEE') then
  select coalesce(sum(case when movement_type in('SOLDE_INITIAL','DOTATION') then qty when movement_type in('RETOUR','PERTE_APPROUVEE') then -qty else 0 end),0)
  into debt from public.rcn_jute_movements where supplier_code=new.supplier_code;
  if debt<new.qty then raise exception 'Retour/perte supérieur au solde fournisseur (% sacs dus)',debt; end if;
 end if;
 new.created_by=auth.uid(); return new;
end $function$
;
CREATE OR REPLACE FUNCTION private.rcn_proc_audit_row()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'private'
AS $function$
declare rid text; v_role text;
begin
 if auth.uid() is null then raise exception 'Authentification requise'; end if;
 select role into v_role from public.profils where user_id=auth.uid() and actif is true;
 if v_role is null then raise exception 'Profil actif requis'; end if;
 rid=coalesce(to_jsonb(new)->>'id',to_jsonb(old)->>'id',to_jsonb(new)->>'supplier_code',to_jsonb(old)->>'supplier_code','?');
 insert into public.rcn_proc_audit_central(table_name,record_id,action,before_data,after_data,actor_id,actor_role)
 values(tg_table_name,rid,tg_op,case when tg_op='INSERT' then null else to_jsonb(old) end,case when tg_op='DELETE' then null else to_jsonb(new) end,auth.uid(),v_role);
 return coalesce(new,old);
end $function$
;
CREATE OR REPLACE FUNCTION public.sacherie_guard_mouvement()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$ declare v_req public.bag_movement_requests%rowtype; begin if new.type='DOTATION_RT' then if new.request_id is null then raise exception 'Approval BM requis : request_id absent'; end if; select * into v_req from public.bag_movement_requests where id=new.request_id for update; if not found or v_req.status<>'APPROVED' then raise exception 'Approval BM requis ou demande non approuvée'; end if; if v_req.expires_at is null or v_req.expires_at<now() then raise exception 'Approval expiré'; end if; if exists(select 1 from public.sacs_mouvements where request_id=new.request_id) then raise exception 'Approval déjà utilisé'; end if; if new.source<>'CLUSTER' or new.destination<>'RT' then raise exception 'Flux DOTATION_RT invalide'; end if; if coalesce(new.rt_id,'')<>v_req.rt_id then raise exception 'RT du mouvement différent du RT approuvé'; end if; if upper(coalesce(new.cluster,''))<>upper(v_req.cluster) then raise exception 'Cluster du mouvement différent du cluster approuvé'; end if; if new.quantite>coalesce(v_req.approved_qty,0) then raise exception 'Quantité exécutée supérieure à la quantité approuvée'; end if; if coalesce(new.executed_qty,new.quantite)<>new.quantite then raise exception 'executed_qty incohérent avec quantite'; end if; if coalesce(new.approved_qty,0)<>coalesce(v_req.approved_qty,0) then raise exception 'approved_qty incohérent avec approval'; end if; if new.bag_state is distinct from 'EMPTY' then raise exception 'Une dotation RT remet des sacs EMPTY'; end if; end if; return new; end $function$
;
create or replace function public.sacherie_guard_mouvement_update()
returns trigger language plpgsql security definer set search_path to 'public'
as $fn$
declare
  v_fige text[] := array['local_id','date','type','source','destination','cluster','rt_id','rt_nom','producteur_id','producteur_nom','quantite','created_by','created_at','request_id','bag_movement_code','approved_qty','executed_qty','bag_state'];
  v_col text;
  v_old jsonb := to_jsonb(old);
  v_new jsonb := to_jsonb(new);
begin
  if new.type = 'DOTATION_RT' and old.type is distinct from 'DOTATION_RT' then
    raise exception 'Requalification en DOTATION_RT interdite : une dotation RT se cree uniquement par le workflow approuve (sacherie_executer_demande)' using errcode = '42501';
  end if;
  foreach v_col in array v_fige loop
    if v_old -> v_col is distinct from v_new -> v_col then
      raise exception 'Colonne % non modifiable sur un mouvement enregistre. Passer par un contre-mouvement (correction_of).', v_col using errcode = '42501';
    end if;
  end loop;
  return new;
end
$fn$;
create or replace function public.sacherie_guard_mouvement_delete()
returns trigger language plpgsql security definer set search_path to 'public'
as $fn$
begin
  raise exception 'Suppression interdite : un mouvement de sacs enregistre est definitif. Passer par un contre-mouvement (correction_of).' using errcode = '42501';
end
$fn$;
CREATE OR REPLACE FUNCTION public.aflp_bag_allocation_guard()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public', 'pg_temp'
AS $function$
declare v_limit integer; v_other integer;
begin
  select approved_qty into v_limit from public.aflp_bag_envelopes where id=new.envelope_id and status='GM_APPROVED' for update;
  if not found then raise exception 'Enveloppe AFLP GM approuvée requise'; end if;
  select coalesce(sum(allocated_qty),0)::integer into v_other from public.aflp_bag_cluster_allocations where envelope_id=new.envelope_id and id is distinct from new.id;
  if v_other+new.allocated_qty>v_limit then raise exception 'Allocation cluster supérieure au solde de l’enveloppe AFLP'; end if;
  return new;
end $function$
;
CREATE OR REPLACE FUNCTION public.sacherie_reservations_rt(p_rt_id text, p_exclude_request uuid DEFAULT NULL::uuid)
 RETURNS integer
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$ select coalesce(sum(r.approved_qty),0)::integer from public.bag_movement_requests r where r.rt_id=p_rt_id and r.status='APPROVED' and r.expires_at>now() and (p_exclude_request is null or r.id<>p_exclude_request) $function$
;
CREATE OR REPLACE FUNCTION public.sacherie_sacs_sous_responsabilite_rt(p_rt_id text)
 RETURNS integer
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$ select greatest(coalesce(sum(case when coalesce(m.destination,'') in ('RT','PRODUCTEUR') and coalesce(m.source,'') not in ('RT','PRODUCTEUR') then m.quantite when coalesce(m.source,'') in ('RT','PRODUCTEUR') and coalesce(m.destination,'') not in ('RT','PRODUCTEUR') then -m.quantite else 0 end),0),0)::integer from public.sacs_mouvements m where m.rt_id=p_rt_id $function$
;
CREATE OR REPLACE FUNCTION public.sacherie_stock_cluster(p_cluster text)
 RETURNS integer
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$ select greatest(coalesce(sum(case when m.destination='CLUSTER' then m.quantite else 0 end),0)-coalesce(sum(case when m.source='CLUSTER' then m.quantite else 0 end),0),0)::integer from public.sacs_mouvements m where upper(coalesce(m.cluster,''))=upper(coalesce(p_cluster,'')) $function$
;
CREATE OR REPLACE FUNCTION public.sacherie_calculer_plafond(p_rt_id text, p_cycle_id text, p_stock_rcn_kg numeric)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_finance numeric:=0; v_achete numeric:=0; v_restant numeric:=0; v_bags integer:=0; v_reserved integer:=0; v_plafond integer:=0; v_max_new integer:=0; v_available integer:=0; v_cluster text; v_cluster_stock integer:=0;
begin
  if not public.peut_demander_sacherie() then raise exception 'Droit insuffisant pour calculer le plafond Sacherie'; end if;
  if p_stock_rcn_kg is null or p_stock_rcn_kg<0 then raise exception 'Stock RCN vérifié invalide'; end if;
  select coalesce(a.volume_finance_kg,0) into v_finance from public.avances a where a.rt_id=p_rt_id and a.cycle_id=p_cycle_id and a.cycle_statut='OPEN' order by a.created_at desc limit 1;
  if coalesce(v_finance,0)<=0 then raise exception 'Cycle finance OPEN sans volume autorisé en kg'; end if;
  select coalesce(sum(x.poids_net),0) into v_achete from public.achats x where x.rt_id=p_rt_id and x.cycle_id=p_cycle_id and coalesce(x.rejet,false)=false;
  v_restant:=greatest(v_finance-v_achete,0); v_bags:=public.sacherie_sacs_sous_responsabilite_rt(p_rt_id); v_reserved:=public.sacherie_reservations_rt(p_rt_id,null); v_plafond:=floor(((p_stock_rcn_kg+v_restant)*1.10)/80.0); v_max_new:=greatest(v_plafond-v_bags,0); v_available:=greatest(v_max_new-v_reserved,0);
  select coalesce(nullif(btrim(r.cluster),''), nullif(btrim(r.data->>'cluster'),''), '') into v_cluster from public.rt r where r.id::text=p_rt_id and coalesce(r.deleted,false)=false limit 1;
  if not found then raise exception 'RT introuvable dans le référentiel'; end if; if v_cluster='' then raise exception 'RT sans cluster : régulariser le référentiel'; end if;
  v_cluster_stock:=public.sacherie_stock_cluster(v_cluster);
  return jsonb_build_object('volume_finance_kg',v_finance,'volume_achete_cycle_kg',v_achete,'volume_finance_restant_kg',v_restant,'stock_rcn_kg_verified',p_stock_rcn_kg,'bags_already_held',v_bags,'reserved_approved_bags',v_reserved,'system_max_bags',v_plafond,'max_new_bags',v_max_new,'max_new_available',v_available,'cluster_stock',v_cluster_stock);
end $function$
;
CREATE OR REPLACE FUNCTION public.sacherie_creer_demande(p_client_request_id text, p_rt_id text, p_cycle_id text, p_stock_rcn_kg numeric, p_requested_qty integer)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_calc jsonb; v_rt_nom text; v_cluster text; v_zone text; v_prof_cluster text; v_prof_fonction text; v_req public.bag_movement_requests%rowtype; v_code text;
begin
  if not public.peut_demander_sacherie() then raise exception 'Droit insuffisant pour créer une demande'; end if;
  if p_client_request_id is null or btrim(p_client_request_id)='' then raise exception 'Identifiant client de demande obligatoire'; end if;
  if p_requested_qty is null or p_requested_qty<=0 then raise exception 'Quantité invalide'; end if;
  select * into v_req from public.bag_movement_requests where client_request_id=p_client_request_id and requested_by=auth.uid() limit 1;
  if found then return to_jsonb(v_req); end if;
  select coalesce(nullif(btrim(r.nom),''), nullif(btrim(r.data->>'nom'),''), nullif(btrim(r.data->>'rt'),''), r.village_nom), coalesce(nullif(btrim(r.cluster),''), nullif(btrim(r.data->>'cluster'),''), ''), coalesce(nullif(btrim(r.data->>'zone'),''), '') into v_rt_nom,v_cluster,v_zone from public.rt r where r.id::text=p_rt_id and coalesce(r.deleted,false)=false limit 1;
  if not found then raise exception 'RT introuvable dans le référentiel'; end if; if v_cluster='' then raise exception 'RT sans cluster : régulariser le référentiel'; end if;
  if not public.est_bm() then select p.cluster,p.fonction_operationnelle into v_prof_cluster,v_prof_fonction from public.profils p where p.user_id=auth.uid() and p.actif=true limit 1; if v_prof_fonction not in ('Unit Head','Assistant Unit Head') then raise exception 'Seul le Unit Head ou Assistant Unit Head peut demander pour un RT'; end if; if upper(coalesce(v_prof_cluster,''))<>upper(v_cluster) then raise exception 'RT hors du cluster attribué à l utilisateur'; end if; end if;
  v_calc:=public.sacherie_calculer_plafond(p_rt_id,p_cycle_id,p_stock_rcn_kg);
  if p_requested_qty>(v_calc->>'max_new_available')::integer then raise exception 'Quantité demandée supérieure au plafond disponible'; end if;
  v_code:='REQ-'||to_char(current_date,'YYYY')||'-'||public.sacherie_code_cluster(v_cluster)||'-'||lpad(nextval('public.bag_request_seq')::text,6,'0');
  insert into public.bag_movement_requests(client_request_id,request_code,cluster,zone,rt_id,rt_nom,cycle_id,stock_rcn_kg_verified,stock_checked_by,stock_checked_at,stock_source,volume_finance_kg,volume_achete_cycle_kg,volume_finance_restant_kg,bags_already_held,reserved_approved_bags,system_max_bags,max_new_bags,max_new_available,cluster_stock_at_request,requested_qty,status,requested_by,requested_at) values (p_client_request_id,v_code,v_cluster,v_zone,p_rt_id,v_rt_nom,p_cycle_id,p_stock_rcn_kg,auth.uid(),now(),'PHYSICAL_COUNT',(v_calc->>'volume_finance_kg')::numeric,(v_calc->>'volume_achete_cycle_kg')::numeric,(v_calc->>'volume_finance_restant_kg')::numeric,(v_calc->>'bags_already_held')::integer,(v_calc->>'reserved_approved_bags')::integer,(v_calc->>'system_max_bags')::integer,(v_calc->>'max_new_bags')::integer,(v_calc->>'max_new_available')::integer,(v_calc->>'cluster_stock')::integer,p_requested_qty,'PENDING_BM',auth.uid(),now()) returning * into v_req;
  return to_jsonb(v_req);
exception when unique_violation then select * into v_req from public.bag_movement_requests where client_request_id=p_client_request_id and requested_by=auth.uid() limit 1; if found then return to_jsonb(v_req); end if; raise;
end $function$
;
CREATE OR REPLACE FUNCTION public.sacherie_decider_demande(p_request_id uuid, p_action text, p_approved_qty integer DEFAULT NULL::integer, p_comment text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$ declare v_req public.bag_movement_requests%rowtype;v_calc jsonb;v_qty integer;v_other_reserved integer;v_available integer; begin if not public.est_bm() then raise exception 'Seul le Branch Manager peut approuver'; end if; select * into v_req from public.bag_movement_requests where id=p_request_id for update; if not found then raise exception 'Demande introuvable'; end if; if v_req.status not in ('PENDING_BM','HOLD') then raise exception 'Demande déjà traitée'; end if; perform pg_advisory_xact_lock(42027,hashtext(v_req.rt_id)); if upper(p_action)='APPROVE' then v_calc:=public.sacherie_calculer_plafond(v_req.rt_id,v_req.cycle_id,v_req.stock_rcn_kg_verified); v_other_reserved:=public.sacherie_reservations_rt(v_req.rt_id,v_req.id); v_available:=greatest((v_calc->>'max_new_bags')::integer-v_other_reserved,0); v_qty:=coalesce(p_approved_qty,v_req.requested_qty); if v_qty<=0 or v_qty>v_req.requested_qty or v_qty>v_available then raise exception 'Quantité approuvée invalide ou supérieure au plafond disponible'; end if; update public.bag_movement_requests set status='APPROVED',approved_qty=v_qty,approved_by=auth.uid(),approved_at=now(),expires_at=now()+interval '24 hours',approval_comment=p_comment,volume_finance_kg=(v_calc->>'volume_finance_kg')::numeric,volume_achete_cycle_kg=(v_calc->>'volume_achete_cycle_kg')::numeric,volume_finance_restant_kg=(v_calc->>'volume_finance_restant_kg')::numeric,bags_already_held=(v_calc->>'bags_already_held')::integer,reserved_approved_bags=v_other_reserved,system_max_bags=(v_calc->>'system_max_bags')::integer,max_new_bags=(v_calc->>'max_new_bags')::integer,max_new_available=v_available where id=p_request_id returning * into v_req; elsif upper(p_action)='HOLD' then if nullif(btrim(coalesce(p_comment,'')),'') is null then raise exception 'Motif HOLD obligatoire'; end if; update public.bag_movement_requests set status='HOLD',approval_comment=p_comment where id=p_request_id returning * into v_req; elsif upper(p_action)='REJECT' then if nullif(btrim(coalesce(p_comment,'')),'') is null then raise exception 'Motif de rejet obligatoire'; end if; update public.bag_movement_requests set status='REJECTED',approval_comment=p_comment,closed_at=now() where id=p_request_id returning * into v_req; else raise exception 'Action inconnue'; end if; return to_jsonb(v_req); end $function$
;
CREATE OR REPLACE FUNCTION public.sacherie_executer_demande(p_request_id uuid, p_executed_qty integer, p_bag_state text DEFAULT 'EMPTY'::text, p_lot_id text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$ declare v_req public.bag_movement_requests%rowtype;v_mov public.sacs_mouvements%rowtype;v_code text;v_cluster_stock integer; begin if p_executed_qty is null or p_executed_qty<=0 then raise exception 'Quantité exécutée invalide'; end if; select * into v_req from public.bag_movement_requests where id=p_request_id for update; if not found then raise exception 'Demande introuvable'; end if; if not public.peut_executer_sacherie(v_req.cluster) then raise exception 'Seul le Warehouse Keeper ou Assistant Unit Head du cluster peut remettre les sacs'; end if; if v_req.status<>'APPROVED' then raise exception 'Approval BM requis'; end if; if v_req.expires_at is null or v_req.expires_at<now() then raise exception 'Approval expiré'; end if; if p_executed_qty>v_req.approved_qty then raise exception 'Quantité exécutée supérieure à la quantité approuvée'; end if; if upper(coalesce(p_bag_state,'EMPTY'))<>'EMPTY' then raise exception 'La dotation RT doit être EMPTY'; end if; if exists(select 1 from public.sacs_mouvements where request_id=p_request_id) then raise exception 'Approval déjà utilisé'; end if; perform pg_advisory_xact_lock(42027,hashtext(v_req.rt_id)); perform pg_advisory_xact_lock(42028,hashtext(upper(v_req.cluster))); v_cluster_stock:=public.sacherie_stock_cluster(v_req.cluster); if v_cluster_stock<p_executed_qty then raise exception 'Stock sacs cluster insuffisant'; end if; v_code:='BAG-'||to_char(current_date,'YYYY')||'-'||public.sacherie_code_cluster(v_req.cluster)||'-'||lpad(nextval('public.bag_movement_seq')::text,6,'0'); insert into public.sacs_mouvements(local_id,date,type,source,destination,cluster,rt_id,rt_nom,quantite,observation,created_by,created_by_nom,created_at,request_id,bag_movement_code,approved_qty,executed_qty,bag_state,lot_id,business_status,issued_by,issued_at) values(gen_random_uuid()::text,current_date,'DOTATION_RT','CLUSTER','RT',v_req.cluster,v_req.rt_id,v_req.rt_nom,p_executed_qty,'Execution Sacherie V2 '||v_req.request_code,auth.uid(),null,now(),v_req.id,v_code,v_req.approved_qty,p_executed_qty,'EMPTY',null,case when p_executed_qty<v_req.approved_qty then 'PARTIALLY_EXECUTED' else 'EXECUTED' end,auth.uid(),now()) returning * into v_mov; update public.bag_movement_requests set status=case when p_executed_qty<approved_qty then 'PARTIALLY_EXECUTED' else 'EXECUTED' end,closed_at=now() where id=v_req.id; return to_jsonb(v_mov); end $function$
;
create view public.sacherie_ct_global_stock with (security_invoker=true) as  SELECT (COALESCE(sum(s.qty), (0)::bigint))::integer AS total,
    (COALESCE(sum(s.qty) FILTER (WHERE (s.state = 'UTILISABLE'::text)), (0)::bigint))::integer AS vides,
    (COALESCE(sum(s.qty) FILTER (WHERE (s.state = 'PLEIN'::text)), (0)::bigint))::integer AS pleins,
    (COALESCE(sum(s.qty) FILTER (WHERE (s.state = 'EN_TRANSIT'::text)), (0)::bigint))::integer AS transit,
    (COALESCE(sum(s.qty) FILTER (WHERE (s.state = 'DECHIRE'::text)), (0)::bigint))::integer AS dechires,
    (COALESCE(sum(s.qty) FILTER (WHERE (s.state = 'A_REPARER'::text)), (0)::bigint))::integer AS a_reparer,
    (COALESCE(sum(s.qty) FILTER (WHERE (s.state = 'REPARE'::text)), (0)::bigint))::integer AS repares,
    (COALESCE(sum(s.qty) FILTER (WHERE (s.state = 'REFORME'::text)), (0)::bigint))::integer AS rebut,
    COALESCE(( SELECT (sum(x.qty))::integer AS sum FROM rcn_jute_loss_requests x
          WHERE ((x.ledger = 'INTERNE'::text) AND (x.statut = 'APPROUVE'::text))), 0) AS pertes_approuvees,
    COALESCE(( SELECT (sum(x.qty))::integer AS sum FROM rcn_jute_loss_requests x
          WHERE ((x.ledger = 'INTERNE'::text) AND (x.statut = 'SOUMIS'::text))), 0) AS pertes_en_attente
   FROM (rcn_jute_v_stock s JOIN rcn_jute_locations l ON ((l.code = s.location_code)))
  WHERE ((COALESCE(l.scope_type, ''::text) = ANY (ARRAY['CLUSTER'::text, 'RT'::text, 'PRODUCTEUR'::text, 'HUB'::text, 'FACTORY'::text, 'TRANSIT'::text, 'REPARATION'::text, 'REBUT'::text])) OR (l.code ~~ 'AFLP-%'::text));
