/* FIELD BUYING — moteur Operations natif unique.
   Principe : réutiliser les tables/RPC canoniques, ne jamais revenir vers l'ancien shell. */
(function (global) {
'use strict';

function esc(v){return String(v==null?'':v).replace(/[&<>\"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c];});}
function n(v){var x=Number(v||0);return isFinite(x)?x:0;}
function money(v){return new Intl.NumberFormat('fr-FR',{maximumFractionDigits:0}).format(n(v))+' FCFA';}
function mt(v){return (n(v)/1000).toLocaleString('fr-FR',{maximumFractionDigits:1})+' MT';}
function date(v){if(!v)return'—';try{return new Intl.DateTimeFormat('fr-FR').format(new Date(v));}catch(e){return esc(v);}}
function routeParts(){return(location.hash||'#overview').slice(1).split('/').map(function(x){try{return decodeURIComponent(x);}catch(e){return x;}});}
function route(){return routeParts()[0]||'overview';}
function badge(s){var x=String(s||'').toUpperCase(),c=/BLOQ|REFUS|ERREUR|CRIT|EXPIR/.test(x)?'danger':/ACTIF|APPROUV|RECU|CLOS|OK|VALID/.test(x)?'ok':/ATTENT|PENDING|PARTIAL|REVIEW|A REVOIR|À REVOIR/.test(x)?'warn':'info';return'<span class="badge '+c+'">'+esc(s||'—')+'</span>';}
function head(t,s,a){return'<div class="ops-route-head"><div><h1>'+esc(t)+'</h1><p>'+esc(s||'')+'</p></div><div class="ops-route-actions">'+(a||'')+'</div></div>';}
function kpis(xs){return'<section class="kpi-grid">'+xs.map(function(x){return'<div class="kpi '+(x[3]||'')+'"><small>'+esc(x[0])+'</small><b>'+esc(x[1])+'</b><span>'+esc(x[2]||'')+'</span></div>';}).join('')+'</section>';}
function table(h,rs){if(!rs.length)return'<div class="ops-empty">Aucune donnée disponible.</div>';return'<div class="table-wrap"><table><thead><tr>'+h.map(function(x){return'<th>'+esc(x)+'</th>';}).join('')+'</tr></thead><tbody>'+rs.join('')+'</tbody></table></div>';}
function card(x){return'<section class="card">'+x+'</section>';}
function empty(x){return'<div class="ops-empty">'+esc(x)+'</div>';}
function q(id){return document.getElementById(id);}

var root=null,sb=null,profile={},clientPromise=null;
function makeClient(){if(sb)return sb;if(global.supabase&&global.ANAGROCI_SUPABASE_URL&&global.ANAGROCI_SUPABASE_ANON)sb=global.supabase.createClient(global.ANAGROCI_SUPABASE_URL,global.ANAGROCI_SUPABASE_ANON);return sb;}
function client(){if(sb)return Promise.resolve(sb);if(clientPromise)return clientPromise;clientPromise=new Promise(function(resolve){if(makeClient())return resolve(sb);var k=0,t=setInterval(function(){k++;if(makeClient()){clearInterval(t);resolve(sb);}else if(k>120){clearInterval(t);resolve(null);}},50);});return clientPromise;}
async function rows(t,c,l){var x=await client();if(!x)return[];var r=await x.from(t).select(c||'*').limit(l||500);if(r.error)throw new Error(r.error.message);return r.data||[];}
async function rpc(name,args){var x=await client();if(!x)throw new Error('Connexion indisponible');var r=await x.rpc(name,args||{});if(r.error)throw new Error(r.error.message);return r.data;}
async function user(){var x=await client();if(!x)return null;var s=await x.auth.getSession(),u=s.data&&s.data.session&&s.data.session.user;if(!u)return null;var p=await x.from('profils').select('nom,role,actif').eq('user_id',u.id).maybeSingle();if(!p.error&&p.data)profile=p.data;profile.user_id=u.id;return profile;}

var TTL=45000,store={};
var FieldBuyingStore={get:function(key,loader,ttl){var z=store[key],now=Date.now(),life=ttl||TTL;if(z&&z.data!==undefined&&(now-z.at)<life)return Promise.resolve(z.data);if(z&&z.promise)return z.promise;var p=Promise.resolve().then(loader).then(function(d){store[key]={data:d,at:Date.now()};return d;}).catch(function(e){delete store[key];throw e;});store[key]={promise:p,at:now};return p;},invalidate:function(){[].slice.call(arguments).forEach(function(k){delete store[k];});},clear:function(){store={};}};
function base(){return FieldBuyingStore.get('base',function(){return Promise.all([
 rows('villages','id,village,region,departement,cluster,cluster_code,gps_lat,gps_lng,statut,deleted,data',500),
 rows('rt','id,id_rt,nom,telephone,village_id,village_nom,cluster,statut,deleted,data,updated_at',500),
 rows('producteurs','id,code,nom,prenoms,telephone,village_id,village_nom,rt_id,statut,operational_status,passport_stage,passport_completion,risk_profile,possible_duplicate,review_required,deleted,updated_at,data',1000),
 rows('achats','id,date,cluster,village_id,village_nom,rt_id,rt_nom,producteur_id,producteur_nom,producteur_code,poids_net,prix_kg,montant,nb_sacs,kor,humidite,mode_paiement,numero_recu,statut_validation,stock_statut,cash_statut,rejet,created_at',1000),
 rows('avances','id,date,cluster,rt_id,rt_nom,montant,statut,cycle_id,cycle_statut,override_bm,created_at',500)
 ]).then(function(a){return{villages:a[0].filter(function(x){return!x.deleted;}),rt:a[1].filter(function(x){return!x.deleted;}),prod:a[2].filter(function(x){return!x.deleted;}),achats:a[3].filter(function(x){return!x.rejet;}),avances:a[4]};});});}
function bagData(){return FieldBuyingStore.get('bags',function(){return Promise.all([rows('aflp_bag_envelopes','*',50),rows('aflp_bag_cluster_allocations','*',100),rows('ops_bag_requests','*',500),rows('ops_bag_releases','*',1000),rows('sacs_mouvements','id,date,cluster,rt_id,rt_nom,type_mouvement,quantite,producteur_id,producteur_nom,created_at',1000)]).then(function(a){return{env:a[0],alloc:a[1],req:a[2],rel:a[3],mov:a[4]};});});}
function traceData(){return FieldBuyingStore.get('trace',function(){return Promise.all([rows('field_lots','*',500),rows('field_rcn_bags','*',1000),rows('field_stock_movements','*',1000),rows('field_shipments','*',500)]).then(function(a){return{lots:a[0],bags:a[1],mov:a[2],ship:a[3]};});});}
function hubsData(){return FieldBuyingStore.get('hubs',function(){return Promise.all([rows('hubs_clusters','*',100),rows('aflp_clusters','*',100),rows('warehouses','*',100)]).then(function(a){return{hubs:a[0].filter(function(x){return!x.deleted;}),clusters:a[1],warehouses:a[2]};});});}

function action(id,label){return'<button class="btn primary ops-cta-create" type="button" onclick="ANAGROCI_FIELD.'+id+'()">'+esc(label)+'</button>';}
function filters(){return'<div class="ops-filter-row"><input id="fbSearch" class="ops-input" placeholder="Rechercher…" oninput="ANAGROCI_FIELD.render()"><select id="fbCluster" class="ops-input" onchange="ANAGROCI_FIELD.render()"><option value="">Tous clusters</option></select></div>';}
function currentFilter(x){var s=q('fbSearch'),c=q('fbCluster'),term=s?String(s.value||'').toLowerCase():'',cl=c?c.value:'';return(!cl||String(x.cluster||'')===cl)&&(!term||JSON.stringify(x).toLowerCase().indexOf(term)>=0);}
function hydrateClusters(list){var el=q('fbCluster');if(!el)return;var old=el.value,vals={};list.forEach(function(x){if(x.cluster)vals[x.cluster]=1;});Object.keys(vals).sort().forEach(function(v){var o=document.createElement('option');o.value=v;o.textContent=v;el.appendChild(o);});el.value=old;}

function overlay(title,html){var old=q('fbModalRoot');if(!old){old=document.createElement('div');old.id='fbModalRoot';document.body.appendChild(old);}old.innerHTML='<div class="fb-modal"><div class="fb-modal-box"><div class="fb-modal-head"><h3>'+esc(title)+'</h3><button class="btn secondary" onclick="ANAGROCI_FIELD.closeModal()">Fermer</button></div><div class="fb-modal-body"><div id="fbMsg"></div>'+html+'</div></div></div>';}
function msg(x,ok){var e=q('fbMsg');if(e)e.innerHTML='<div class="notice '+(ok?'ok':'danger')+'">'+esc(x)+'</div>';}
function closeModal(){var e=q('fbModalRoot');if(e)e.innerHTML='';}
async function insert(tableName,row,keys){var x=await client(),r=await x.from(tableName).insert(row).select(keys||'*').single();if(r.error)throw new Error(r.error.message);return r.data;}

async function openVillage(){var b=await base();overlay('Nouveau village','<div class="fb-form-grid"><label>Nom<input id="nvVillage"></label><label>Cluster<input id="nvCluster" list="fbClusters"></label><label>Région<input id="nvRegion"></label><label>Département<input id="nvDept"></label><label>Latitude<input id="nvLat" type="number" step="0.000001"></label><label>Longitude<input id="nvLng" type="number" step="0.000001"></label><label>Statut<select id="nvStatut"><option>Brouillon</option><option>Actif</option></select></label></div><datalist id="fbClusters">'+Array.from(new Set(b.villages.map(function(x){return x.cluster;}).filter(Boolean))).map(function(x){return'<option>'+esc(x)+'</option>';}).join('')+'</datalist><button class="btn primary" onclick="ANAGROCI_FIELD.saveVillage()">Enregistrer</button>');}
async function saveVillage(){try{var name=q('nvVillage').value.trim();if(!name)throw new Error('Nom village obligatoire.');await insert('villages',{id:'VIL-'+Date.now(),data:{village:name},village:name,cluster:q('nvCluster').value.trim()||null,region:q('nvRegion').value.trim()||null,departement:q('nvDept').value.trim()||null,gps_lat:q('nvLat').value?Number(q('nvLat').value):null,gps_lng:q('nvLng').value?Number(q('nvLng').value):null,statut:q('nvStatut').value,deleted:false});FieldBuyingStore.invalidate('base');msg('Village créé.',true);setTimeout(function(){closeModal();render();},400);}catch(e){msg(e.message);}}
async function openRT(){var b=await base();overlay('Nouveau RT','<div class="fb-form-grid"><label>Nom<input id="nrNom"></label><label>Téléphone<input id="nrTel"></label><label>Village<select id="nrVillage"><option value="">Sélectionner</option>'+b.villages.map(function(v){return'<option value="'+esc(v.id)+'" data-name="'+esc(v.village)+'" data-cluster="'+esc(v.cluster||'')+'">'+esc(v.village)+' · '+esc(v.cluster||'')+'</option>';}).join('')+'</select></label><label>Activité<input id="nrActivite" placeholder="Producteur, commerçant…"></label><label>Statut<select id="nrStatut"><option>Pressenti</option><option>Actif</option></select></label></div><button class="btn primary" onclick="ANAGROCI_FIELD.saveRT()">Enregistrer</button>');}
async function saveRT(){try{var nom=q('nrNom').value.trim(),sel=q('nrVillage'),o=sel.options[sel.selectedIndex];if(!nom)throw new Error('Nom RT obligatoire.');await insert('rt',{id:'RT-'+Date.now(),data:{nom:nom,telephone:q('nrTel').value.trim()||null,activite:q('nrActivite').value.trim()||null},nom:nom,telephone:q('nrTel').value.trim()||null,village_id:sel.value||null,village_nom:o&&o.dataset.name||null,cluster:o&&o.dataset.cluster||null,statut:q('nrStatut').value,deleted:false});FieldBuyingStore.invalidate('base');msg('RT créé. Les gardes anti-doublon serveur restent applicables.',true);setTimeout(function(){closeModal();render();},400);}catch(e){msg(e.message);}}
async function openFarmer(){var b=await base();overlay('Nouveau producteur','<div class="fb-form-grid"><label>Nom<input id="npNom"></label><label>Prénoms<input id="npPrenoms"></label><label>Téléphone<input id="npTel"></label><label>Village<select id="npVillage" onchange="ANAGROCI_FIELD.syncFarmerRT()"><option value="">Sélectionner</option>'+b.villages.map(function(v){return'<option value="'+esc(v.id)+'" data-name="'+esc(v.village)+'">'+esc(v.village)+' · '+esc(v.cluster||'')+'</option>';}).join('')+'</select></label><label>RT<select id="npRT"><option value="">Aucun</option>'+b.rt.map(function(r){return'<option value="'+esc(r.id)+'" data-village="'+esc(r.village_id||'')+'">'+esc(r.nom)+' · '+esc(r.village_nom||'')+'</option>';}).join('')+'</select></label><label>Statut<select id="npStatut"><option>Identifié</option><option>Actif</option></select></label></div><div class="notice ok"><b>Campagne 2027 :</b> parcelle/GPS facultatif. Le producteur peut être créé et acheter sans parcelle.</div><button class="btn primary" onclick="ANAGROCI_FIELD.saveFarmer()">Enregistrer</button>');}
function syncFarmerRT(){var v=q('npVillage'),r=q('npRT');if(!v||!r)return;[].slice.call(r.options).forEach(function(o){o.hidden=!!(o.dataset.village&&o.dataset.village!==v.value);});if(r.selectedOptions[0]&&r.selectedOptions[0].hidden)r.value='';}
async function saveFarmer(){try{var nom=q('npNom').value.trim(),v=q('npVillage'),o=v.options[v.selectedIndex];if(!nom||!v.value)throw new Error('Nom et village obligatoires.');var dup=await rpc('farmer_possible_duplicates',{p_nom:nom,p_telephone:q('npTel').value.trim()||null,p_village_id:v.value,p_exclude_id:null});if(Array.isArray(dup)&&dup.length){msg('Doublon potentiel détecté. Vérifiez le Farmer Registry avant de créer.');return;}await insert('producteurs',{id:'FAR-'+Date.now(),data:{nom:nom,prenoms:q('npPrenoms').value.trim()||null},nom:nom,prenoms:q('npPrenoms').value.trim()||null,telephone:q('npTel').value.trim()||null,village_id:v.value,village_nom:o&&o.dataset.name||null,rt_id:q('npRT').value||null,statut:q('npStatut').value,deleted:false});FieldBuyingStore.invalidate('base');msg('Producteur créé. Farmer ID attribué par le moteur canonique.',true);setTimeout(function(){closeModal();render();},500);}catch(e){msg(e.message);}}
async function openPurchase(){var b=await base();overlay('Nouvel Achat Bord Champ','<div class="fb-form-grid"><label>Date<input id="naDate" type="date" value="'+new Date().toISOString().slice(0,10)+'"></label><label>Producteur<select id="naFarmer" onchange="ANAGROCI_FIELD.fillPurchaseRefs()"><option value="">Sélectionner</option>'+b.prod.map(function(p){return'<option value="'+esc(p.id)+'" data-code="'+esc(p.code||'')+'" data-name="'+esc((p.nom||'')+' '+(p.prenoms||''))+'" data-village="'+esc(p.village_id||'')+'" data-village-name="'+esc(p.village_nom||'')+'" data-rt="'+esc(p.rt_id||'')+'">'+esc(p.code||p.id)+' · '+esc(p.nom||'')+' · '+esc(p.village_nom||'')+'</option>';}).join('')+'</select></label><label>Poids net kg<input id="naWeight" type="number" min="1" step="0.1"></label><label>Prix FCFA/kg<input id="naPrice" type="number" min="1" step="1"></label><label>Nombre sacs<input id="naBags" type="number" min="0" step="1"></label><label>Mode paiement<select id="naPay"><option>Espèces</option><option>Mobile Money</option></select></label><label>Référence/reçu<input id="naReceipt"></label><label>KOR<input id="naKor" type="number" step="0.1"></label><label>Humidité %<input id="naHum" type="number" step="0.1"></label></div><div id="naContext" class="notice ok">Sélectionnez un producteur.</div><button class="btn primary" onclick="ANAGROCI_FIELD.savePurchase()">Enregistrer l’achat</button>');}
async function fillPurchaseRefs(){var b=await base(),s=q('naFarmer'),o=s.options[s.selectedIndex],p=b.prod.find(function(x){return x.id===s.value;}),r=p&&b.rt.find(function(x){return x.id===p.rt_id;});q('naContext').textContent=p?'Farmer ID '+(p.code||p.id)+' · '+(p.village_nom||'—')+' · RT '+(r?r.nom:'—')+' · Parcelle non bloquante':'Sélectionnez un producteur.';}
async function savePurchase(){try{var b=await base(),s=q('naFarmer'),p=b.prod.find(function(x){return x.id===s.value;});if(!p)throw new Error('Producteur obligatoire.');var r=b.rt.find(function(x){return x.id===p.rt_id;}),v=b.villages.find(function(x){return x.id===p.village_id;}),w=Number(q('naWeight').value),price=Number(q('naPrice').value);if(!(w>0&&price>0))throw new Error('Poids et prix obligatoires.');await insert('achats',{date:q('naDate').value,cluster:(r&&r.cluster)||(v&&v.cluster)||null,village_id:p.village_id,village_nom:p.village_nom,rt_id:p.rt_id||null,rt_nom:r&&r.nom||null,producteur_id:p.id,producteur_nom:[p.nom,p.prenoms].filter(Boolean).join(' '),producteur_code:p.code||null,poids_net:w,prix_kg:price,montant:w*price,nb_sacs:Number(q('naBags').value||0),mode_paiement:q('naPay').value,numero_recu:q('naReceipt').value.trim()||null,kor:q('naKor').value?Number(q('naKor').value):null,humidite:q('naHum').value?Number(q('naHum').value):null,rejet:false});FieldBuyingStore.invalidate('base','trace');msg('Achat enregistré. Les gardes caisse, reçu et intégrité serveur restent applicables.',true);setTimeout(function(){closeModal();render();},500);}catch(e){msg(e.message);}}
async function openBagRequest(){var b=await base(),u=await user();overlay('Nouvelle demande RT · Sacherie AFLP','<div class="fb-form-grid"><label>RT<select id="nbRT"><option value="">Sélectionner</option>'+b.rt.map(function(r){return'<option value="'+esc(r.id)+'" data-cluster="'+esc(r.cluster||'')+'">'+esc(r.id_rt||r.id)+' · '+esc(r.nom)+' · '+esc(r.cluster||'')+'</option>';}).join('')+'</select></label><label>Quantité demandée<input id="nbQty" type="number" min="1" step="1"></label><label>Campagne<input id="nbCampaign" value="2027"></label></div><div class="notice ok"><b>Règle :</b> approbation et sortie physique sont deux étapes distinctes. Une sortie partielle ne clôture pas l’autorisation.</div><button class="btn primary" onclick="ANAGROCI_FIELD.saveBagRequest()">Soumettre la demande</button>');if(!u||!u.user_id)msg('Session utilisateur requise pour créer une demande.');}
async function saveBagRequest(){try{var u=await user(),sel=q('nbRT'),o=sel.options[sel.selectedIndex],qty=Number(q('nbQty').value);if(!u||!u.user_id)throw new Error('Session utilisateur introuvable.');if(!sel.value||!(qty>0))throw new Error('RT et quantité obligatoires.');var now=Date.now(),code='AFLP-'+String(now).slice(-8);await insert('ops_bag_requests',{client_request_id:'web-'+now+'-'+Math.random().toString(36).slice(2,8),request_code:code,channel:'FIELD_BUYING',campaign:q('nbCampaign').value.trim()||'2027',cluster:o.dataset.cluster||null,rt_id:sel.value,requested_qty:qty,released_qty:0,received_qty:0,status:'REQUESTED',requested_by:u.user_id,metadata:{source:'operations-field-buying'}});FieldBuyingStore.invalidate('bags');msg('Demande créée. Aucune sortie physique n’a été enregistrée.',true);setTimeout(function(){closeModal();render();},500);}catch(e){msg(e.message);}}

async function renderOverview(b){var total=b.achats.reduce(function(t,x){return t+n(x.poids_net);},0),goal=3000000,pct=Math.min(100,total/goal*100),today=new Date().toISOString().slice(0,10),todayKg=b.achats.filter(function(x){return x.date===today;}).reduce(function(t,x){return t+n(x.poids_net);},0),activeRT=b.rt.filter(function(x){return!/INACTIF|SUSPENDU/i.test(x.statut||'');}).length;root.innerHTML=head('FIELD BUYING','Pilotage terrain AFLP 2027 · Achat Bord Champ',action('openPurchase','+ Nouvel achat'))+kpis([['Objectif campagne','3 000 MT',pct.toFixed(1)+' % atteint'],['RCN acheté',mt(total),b.achats.length+' achats'],['Achats du jour',mt(todayKg),today],['Producteurs',String(b.prod.length),'Farmer Registry'],['RT actifs',String(activeRT),'référentiel'],['Villages',String(b.villages.length),'actifs']])+card('<h2>Progression campagne</h2><div class="fb-progress"><div style="width:'+pct.toFixed(2)+'%"></div></div><p>'+mt(total)+' / 3 000 MT</p>')+card(table(['Date','Farmer ID','Producteur','RT','Village','Poids','Prix','Montant'],b.achats.slice().sort(function(a,z){return String(z.date).localeCompare(String(a.date));}).slice(0,20).map(function(x){return'<tr><td>'+date(x.date)+'</td><td class="mono">'+esc(x.producteur_code||'—')+'</td><td>'+esc(x.producteur_nom||'—')+'</td><td>'+esc(x.rt_nom||'—')+'</td><td>'+esc(x.village_nom||'—')+'</td><td>'+mt(x.poids_net)+'</td><td>'+n(x.prix_kg)+'</td><td>'+money(x.montant)+'</td></tr>';})));}
async function renderCensus(b){root.innerHTML=head('Recensement','Créer immédiatement les référentiels terrain.',action('openVillage','+ Nouveau village')+action('openFarmer','+ Nouveau producteur')+action('openRT','+ Nouveau RT'))+kpis([['Villages',String(b.villages.length),'référentiel'],['Producteurs',String(b.prod.length),'Farmer Registry'],['RT',String(b.rt.length),'référentiel'],['Doublons producteurs',String(b.prod.filter(function(x){return x.possible_duplicate;}).length),'à revoir']])+card('<h2>Derniers référentiels</h2>'+table(['Type','ID','Nom','Village','Cluster','Statut'],b.villages.slice(-10).map(function(v){return'<tr><td>Village</td><td class="mono">'+esc(v.id)+'</td><td>'+esc(v.village||'—')+'</td><td>'+esc(v.village||'—')+'</td><td>'+esc(v.cluster||'—')+'</td><td>'+badge(v.statut)+'</td></tr>';}).concat(b.rt.slice(-10).map(function(r){return'<tr><td>RT</td><td class="mono">'+esc(r.id_rt||r.id)+'</td><td>'+esc(r.nom||'—')+'</td><td>'+esc(r.village_nom||'—')+'</td><td>'+esc(r.cluster||'—')+'</td><td>'+badge(r.statut)+'</td></tr>';}))));}
async function renderFarmers(b){root.innerHTML=head('Producteurs','Farmer Registry et Farmer Passport sans seconde identité.',action('openFarmer','+ Nouveau producteur'))+filters()+card(table(['Farmer ID','Nom','Téléphone','Village','RT','Passport','Complétude','Risque','Parcelle'],b.prod.filter(currentFilter).map(function(p){var r=b.rt.find(function(x){return x.id===p.rt_id;}),parcel=(p.data&&p.data.parcelle)?'Disponible':'À compléter après campagne';return'<tr><td class="mono">'+esc(p.code||p.id)+'</td><td>'+esc([p.nom,p.prenoms].filter(Boolean).join(' '))+'</td><td>'+esc(p.telephone||'—')+'</td><td>'+esc(p.village_nom||'—')+'</td><td>'+esc(r?r.nom:'—')+'</td><td>'+badge(p.passport_stage)+'</td><td>'+n(p.passport_completion)+' %</td><td>'+badge(p.risk_profile)+'</td><td>'+esc(parcel)+'</td></tr>';})));hydrateClusters(b.villages);}
async function renderRT(b){root.innerHTML=head('RT & Villages','Gestion référentielle, affectations et anomalies.',action('openVillage','+ Nouveau village')+action('openRT','+ Nouveau RT'))+filters()+card(table(['RT ID','Nom','Téléphone','Village','Cluster','Statut','Producteurs','Achats','Dernière activité'],b.rt.filter(currentFilter).map(function(r){var pc=b.prod.filter(function(p){return p.rt_id===r.id;}).length,ac=b.achats.filter(function(a){return a.rt_id===r.id||a.rt_nom===r.nom;}).length;return'<tr><td class="mono">'+esc(r.id_rt||r.id)+'</td><td>'+esc(r.nom||'—')+'</td><td>'+esc(r.telephone||'—')+'</td><td>'+esc(r.village_nom||'—')+'</td><td>'+esc(r.cluster||'—')+'</td><td>'+badge(r.statut)+'</td><td>'+pc+'</td><td>'+ac+'</td><td>'+date(r.updated_at)+'</td></tr>';})));hydrateClusters(b.rt);}
async function renderPurchases(b){var total=b.achats.reduce(function(t,x){return t+n(x.poids_net);},0),val=b.achats.reduce(function(t,x){return t+n(x.montant);},0);root.innerHTML=head('Achat Bord Champ','Producteur → Achat → Sacs → Lot → Stock → Traceability.',action('openPurchase','+ Nouvel achat'))+kpis([['Volume campagne',mt(total),b.achats.length+' achats'],['Valeur',money(val),'montant achats'],['Prix moyen',total?money(val/total).replace(' FCFA',' FCFA/kg'):'0 FCFA/kg','pondéré'],['Producteurs vendeurs',String(new Set(b.achats.map(function(x){return x.producteur_id||x.producteur_code;})).size),'uniques'],['RT actifs achat',String(new Set(b.achats.map(function(x){return x.rt_id||x.rt_nom;})).size),'campagne']])+filters()+card(table(['Date','Farmer ID','Producteur','RT','Village','Poids','Sacs','Prix','Montant','Paiement','Lot/Stock'],b.achats.filter(currentFilter).map(function(x){return'<tr><td>'+date(x.date)+'</td><td class="mono">'+esc(x.producteur_code||'—')+'</td><td>'+esc(x.producteur_nom||'—')+'</td><td>'+esc(x.rt_nom||'—')+'</td><td>'+esc(x.village_nom||'—')+'</td><td>'+mt(x.poids_net)+'</td><td>'+n(x.nb_sacs)+'</td><td>'+n(x.prix_kg)+'</td><td>'+money(x.montant)+'</td><td>'+esc(x.mode_paiement||'—')+'</td><td>'+badge(x.stock_statut)+'</td></tr>';})));hydrateClusters(b.achats);}
async function renderBags(){var d=await bagData(),env=d.env.find(function(x){return String(x.campaign).indexOf('2027')>=0;})||d.env[0],alloc=d.alloc.reduce(function(t,x){return t+n(x.allocated_qty);},0),released=d.rel.reduce(function(t,x){return t+n(x.qty);},0),pending=d.req.filter(function(x){return /REQUESTED|PENDING|APPROVED|PARTIAL/i.test(x.status||'');}).length;root.innerHTML=head('Sacherie AFLP','Enveloppe → allocation cluster → demande RT → approval → releases → réception.',action('openBagRequest','+ Nouvelle demande RT'))+kpis([['Enveloppe campagne',String(env?n(env.approved_qty):0)+' sacs','GM approved'],['Alloués clusters',String(alloc)+' sacs','allocations'],['Sortis physiquement',String(released)+' sacs','releases'],['Demandes ouvertes',String(pending),'à suivre'],['Multi-release','Actif','approval ≠ release']])+card(table(['Demande','Cluster','RT','Demandé','Approuvé','Sorti','Reçu','Statut','Expiration'],d.req.slice().sort(function(a,b){return new Date(b.requested_at)-new Date(a.requested_at);}).map(function(x){return'<tr><td class="mono">'+esc(x.request_code)+'</td><td>'+esc(x.cluster||'—')+'</td><td class="mono">'+esc(x.rt_id||'—')+'</td><td>'+n(x.requested_qty)+'</td><td>'+n(x.approved_qty)+'</td><td>'+n(x.released_qty)+'</td><td>'+n(x.received_qty)+'</td><td>'+badge(x.status)+'</td><td>'+date(x.expires_at)+'</td></tr>';})))+card('<h2>Sorties physiques</h2>'+table(['Date','Demande','Quantité','Origine','Destination','Reçu par'],d.rel.slice().sort(function(a,b){return new Date(b.released_at)-new Date(a.released_at);}).slice(0,100).map(function(x){return'<tr><td>'+date(x.released_at)+'</td><td class="mono">'+esc(x.request_id)+'</td><td>'+n(x.qty)+'</td><td>'+esc(x.source_location_code)+'</td><td>'+esc(x.destination_location_code)+'</td><td>'+esc(x.received_by||'—')+'</td></tr>';})));}
async function renderCash(b){var tot=b.avances.reduce(function(t,x){return t+n(x.montant);},0),open=b.avances.filter(function(x){return /OPEN|ACTIVE|ACTIF/i.test(x.cycle_statut||x.statut||'');}).length;root.innerHTML=head('Caisse & Avances','Avances RT, cycles et contrôle des fonds.')+kpis([['Avances émises',money(tot),b.avances.length+' lignes'],['Cycles ouverts',String(open),'à réconcilier'],['Overrides BM',String(b.avances.filter(function(x){return x.override_bm;}).length),'exceptions']])+card(table(['Date','RT','Cluster','Montant','Cycle','Statut','Override BM'],b.avances.map(function(x){return'<tr><td>'+date(x.date)+'</td><td>'+esc(x.rt_nom||x.rt_id||'—')+'</td><td>'+esc(x.cluster||'—')+'</td><td>'+money(x.montant)+'</td><td class="mono">'+esc(x.cycle_id||'—')+'</td><td>'+badge(x.cycle_statut||x.statut)+'</td><td>'+(x.override_bm?'Oui':'Non')+'</td></tr>';})));}
async function renderCommand(b){var alerts=[];b.villages.forEach(function(v){if(!b.rt.some(function(r){return r.village_id===v.id;}))alerts.push(['Village sans RT','Critique',v.village,v.cluster]);});b.rt.forEach(function(r){var ac=b.achats.filter(function(a){return a.rt_id===r.id||a.rt_nom===r.nom;});if(!ac.length)alerts.push(['RT sans achat','Attention',r.nom,r.cluster]);});b.prod.filter(function(p){return p.possible_duplicate||p.review_required;}).forEach(function(p){alerts.push(['Producteur à revoir','Attention',p.code||p.id,p.village_nom]);});var tr=await traceData();tr.mov.filter(function(x){return /DISPATCHED|IN_TRANSIT/i.test(x.status||'');}).forEach(function(x){alerts.push(['Stock à évacuer / en transit','Attention',x.movement_code,x.to_label]);});root.innerHTML=head('Command Center','Exceptions et contrôles opérationnels FIELD BUYING.')+kpis([['Alertes',String(alerts.length),'toutes catégories'],['Critiques',String(alerts.filter(function(x){return x[1]==='Critique';}).length),'à traiter']])+card(table(['Type','Sévérité','Objet','Périmètre'],alerts.map(function(x){return'<tr><td>'+esc(x[0])+'</td><td>'+badge(x[1])+'</td><td>'+esc(x[2])+'</td><td>'+esc(x[3]||'—')+'</td></tr>';})));}
async function renderSustainability(b){var s=await Promise.all([rows('farmer_sustainability_baselines','id,producteur_id,campaign,status,finalized_at,created_at',1000),rows('farmer_action_plans','id,producteur_id,status,due_date,severity,created_at',1000)]),m={};b.prod.forEach(function(p){m[p.id]=p;});root.innerHTML=head('Sustainability','Baselines, risques et plans d’action reliés au Farmer Passport.')+kpis([['Baselines',String(s[0].length),'durabilité'],['Finalisées',String(s[0].filter(function(x){return x.status==='FINAL';}).length),'vérifiées'],['Plans ouverts',String(s[1].filter(function(x){return !/CLOSED|DONE|CANCELLED/i.test(x.status||'');}).length),'actions']])+card(table(['Farmer ID','Producteur','Campagne','Statut','Finalisation'],s[0].map(function(x){var p=m[x.producteur_id]||{};return'<tr><td class="mono">'+esc(p.code||x.producteur_id)+'</td><td>'+esc(p.nom||'—')+'</td><td>'+esc(x.campaign||'—')+'</td><td>'+badge(x.status)+'</td><td>'+date(x.finalized_at)+'</td></tr>';})));}
async function renderTrace(){var d=await traceData();root.innerHTML=head('Traceability','Farmer ID → Achat → Lot → Sac → Stock → Shipment → Factory.')+kpis([['Lots terrain',String(d.lots.length),'field_lots'],['Sacs RCN',String(d.bags.length),'field_rcn_bags'],['Mouvements stock',String(d.mov.length),'terrain'],['Shipments',String(d.ship.length),'évacuations']])+card('<h2>Lots</h2>'+table(['Lot','Périmètre','Statut','Scellé','Créé'],d.lots.map(function(x){return'<tr><td class="mono">'+esc(x.lot_code)+'</td><td>'+esc(x.scope_label)+'</td><td>'+badge(x.status)+'</td><td>'+date(x.sealed_at)+'</td><td>'+date(x.created_at)+'</td></tr>';})))+card('<h2>Shipments</h2>'+table(['Shipment','Origine','Destination','Prévu','Expédié','Reçu','Statut'],d.ship.map(function(x){return'<tr><td class="mono">'+esc(x.shipment_code)+'</td><td>'+esc(x.origin_label)+'</td><td>'+esc(x.destination_label)+'</td><td>'+mt(x.planned_qty_kg)+'</td><td>'+mt(x.dispatched_qty_kg)+'</td><td>'+mt(x.received_qty_kg)+'</td><td>'+badge(x.status)+'</td></tr>';})));}
async function renderMap(b){var h=await hubsData();root.innerHTML=head('Hubs & Cartographie','Géographie opérationnelle AFLP : villages, clusters, hubs, Bouaké et Yamoussoukro.')+kpis([['Villages géolocalisés',String(b.villages.filter(function(x){return x.gps_lat&&x.gps_lng;}).length),'/ '+b.villages.length],['Hubs',String(h.hubs.length),'référentiel'],['Warehouses',String(h.warehouses.length),'opérations']])+card('<div id="fbMap" style="height:560px;border-radius:12px;overflow:hidden"></div>');setTimeout(function(){var el=q('fbMap');if(!el||!global.L)return el&&(el.innerHTML=empty('Bibliothèque cartographique indisponible.'));var map=L.map('fbMap').setView([7.69,-5.03],7);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);b.villages.filter(function(v){return v.gps_lat&&v.gps_lng;}).forEach(function(v){var rt=b.rt.filter(function(r){return r.village_id===v.id;}),p=b.prod.filter(function(x){return x.village_id===v.id;}),a=b.achats.filter(function(x){return x.village_id===v.id;}),kg=a.reduce(function(t,x){return t+n(x.poids_net);},0);L.marker([Number(v.gps_lat),Number(v.gps_lng)]).addTo(map).bindPopup('<b>'+esc(v.village)+'</b><br>Cluster: '+esc(v.cluster||'—')+'<br>RT: '+rt.length+'<br>Producteurs: '+p.length+'<br>Achat: '+mt(kg)+'<br>Statut: '+esc(v.statut||'—'));});h.hubs.filter(function(x){return x.gps_lat&&x.gps_lng;}).forEach(function(x){L.circleMarker([Number(x.gps_lat),Number(x.gps_lng)],{radius:8}).addTo(map).bindPopup('<b>'+esc(x.nom)+'</b><br>Hub / cluster<br>Distance usine: '+esc(x.distance_usine_routiere||x.distance_usine_gps||'—')+' km');});},0);}

async function render(){if(!root)return;root.innerHTML='<div class="empty">Chargement…</div>';try{var r=route(),b=await base();if(r==='overview')return renderOverview(b);if(r==='purchases')return renderPurchases(b);if(r==='census')return renderCensus(b);if(r==='farmers')return renderFarmers(b);if(r==='rt')return renderRT(b);if(r==='logistics')return renderMap(b);if(r==='bags')return renderBags();if(r==='cash')return renderCash(b);if(r==='command')return renderCommand(b);if(r==='sustainability')return renderSustainability(b);if(r==='traceability')return renderTrace();return renderOverview(b);}catch(e){root.innerHTML=head('FIELD BUYING','Erreur de chargement')+card('<div class="notice danger">'+esc(e.message)+'</div>');}}

function injectStyles(){if(q('fbNativeStyles'))return;var s=document.createElement('style');s.id='fbNativeStyles';s.textContent='.fb-modal{position:fixed;inset:0;background:rgba(0,0,0,.55);z-index:9999;display:flex;align-items:center;justify-content:center;padding:16px}.fb-modal-box{width:min(880px,100%);max-height:94vh;overflow:auto;background:#fff;border-radius:14px}.fb-modal-head{position:sticky;top:0;background:#053B23;color:#fff;display:flex;align-items:center;justify-content:space-between;padding:14px 16px;z-index:2}.fb-modal-head h3{margin:0}.fb-modal-body{padding:16px}.fb-form-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:12px;margin-bottom:14px}.fb-form-grid label{display:flex;flex-direction:column;gap:5px;font-size:12px;font-weight:700}.fb-form-grid input,.fb-form-grid select,.ops-input{border:1px solid #cbd4c8;border-radius:8px;padding:9px;background:#fff}.ops-filter-row{display:flex;gap:10px;flex-wrap:wrap;margin:0 0 12px}.fb-progress{height:16px;background:#e8ece8;border-radius:999px;overflow:hidden}.fb-progress>div{height:100%;background:#8DC556}.ops-route-actions{display:flex;gap:8px;flex-wrap:wrap}@media(max-width:620px){.fb-modal{padding:0}.fb-modal-box{height:100vh;max-height:100vh;border-radius:0}.fb-form-grid{grid-template-columns:1fr}.ops-route-actions{width:100%}}';document.head.appendChild(s);}

async function init(){root=q('opsRouteView');injectStyles();await user();await render();}
global.ANAGROCI_OPS_ROUTE=render;
global.ANAGROCI_FIELD={render:render,openVillage:openVillage,saveVillage:saveVillage,openRT:openRT,saveRT:saveRT,openFarmer:openFarmer,saveFarmer:saveFarmer,syncFarmerRT:syncFarmerRT,openPurchase:openPurchase,fillPurchaseRefs:fillPurchaseRefs,savePurchase:savePurchase,openBagRequest:openBagRequest,saveBagRequest:saveBagRequest,closeModal:closeModal,store:FieldBuyingStore};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})(window);
