/* Recherche transverse Traceability 360 — projection SQL, aucune duplication transactionnelle.
   Objets traçables : Farmer, LBA, Funding Cycle, généalogie RCN, transfert, COOPÉRATIVE (AFLP 2027),
   livraison de coopérative et LOT Warehouse avec son origine (canal, coopérative, producteurs). */
(function(g){'use strict';
function esc(v){return String(v==null?'':v).replace(/[&<>\"]/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c];});}
var client=null;
function waitClient(){if(client)return Promise.resolve(client);return new Promise(function(resolve){var n=0,t=setInterval(function(){n++;if(g.supabase&&g.ANAGROCI_SUPABASE_URL&&g.ANAGROCI_SUPABASE_ANON){clearInterval(t);client=g.supabase.createClient(g.ANAGROCI_SUPABASE_URL,g.ANAGROCI_SUPABASE_ANON);resolve(client);}else if(n>100){clearInterval(t);resolve(null);}},80);});}
function fmtKg(v){var n=Number(v||0);return n?new Intl.NumberFormat('fr-FR',{maximumFractionDigits:0}).format(n)+' kg':'—';}
function mt(v){return new Intl.NumberFormat('fr-FR',{maximumFractionDigits:1}).format(Number(v||0)/1000)+' MT';}
var LABELS={FARMER_CHAIN:'Chaîne producteur (achat → lot terrain → expédition)',RCN_GENEALOGY:'Généalogie RCN (historique)',LBA:'LBA',FUNDING_CYCLE:'Cycle de financement',STOCK_TRANSFER:'Transfert (historique RCN Trace)',COOPERATIVE:'Coopérative AFLP',COOP_DELIVERY:'Livraison coopérative',WMS_LOT:'LOT Warehouse',
 FARMER:'Producteur (Farmer ID)',RT:'RT',COOP_MEMBER:'Membre de coopérative',PURCHASE:'Achat (reçu / Purchase ID)',PROCUREMENT_ARRIVAL:'Arrivage Procurement',WMS_RECEPTION:'Réception Warehouse',WMS_BIN:'BIN',WMS_TRANSFER:'Transfert WMS'};
var KEYS={producteur_id:'Producteur',farmer_id:'Farmer ID',member_number:'Member ID',followup_rt_id:'RT de suivi',section_id:'Section',receipt:'N° de reçu',local_id:'Identifiant terrain',achat_id:'Purchase ID',rt:'RT',rt_id:'RT',channel:'Canal',amount:'Montant (FCFA)',village:'Village',review_required:'À vérifier',supplier_code:'Fournisseur',supplier:'Fournisseur',truck:'Camion',lot_id:'LOT',source:'Source',source_id:'Référence source',net_kg:'Poids net (kg)',decision:'Décision',stock_type:'Type de stock',capacity_kg:'Capacité (kg)',lots:'LOT',bins:'BIN',seal:'Scellé',dest_is_factory:'Vers l’usine',received_kg:'Reçu (kg)',variance_kg:'Écart (kg)',factory_reception:'Réception usine',lot_code:'Lot terrain',shipment_code:'Expédition',vehicle_plate:'Camion',reception_id:'Réception',factory_lot_id:'Lot usine',origin_channel:'Canal d’origine',cooperatives:'Coopérative(s)',farmers:'Producteurs',villages:'Villages',traceability:'Traçabilité',reception:'Réception',status:'Statut',cooperative:'Coopérative',allocation:'Répartition producteurs',allocated_kg:'Alloué (kg)',arrival:'Arrivage',name:'Nom',cluster:'Cluster',locality:'Localité'};
var VALUES={COOPERATIVE:'Coopérative',AFLP_DIRECT:'Direct RT',MIXTE:'Mixte',TRACABLE_PRODUCTEUR:'Traçable producteur',ALLOCATION_A_COMPLETER:'Allocation à compléter',ORGANISATION_SEULEMENT:'Organisation seulement',TRACABLE:'Traçable producteur',FIELD_BUYING:'Achat Bord Champ',DIRECT:'Direct Supplier',ARRIVED:'Arrivé',SAMPLING:'Échantillonnage',RELEASED:'Libéré',DISPATCHED:'Expédié',RECEIVED:'Reçu',CLOSED:'Clôturé',APPROVED:'Approuvé',REQUESTED:'Demandé',IN_TRANSIT:'En transit',OPEN:'Ouvert',true:'Oui',false:'Non',ALLOUEE_PREVISION:'Allouée (prévision)',PLANIFIEE:'Planifiée',RECUE:'Reçue',EN_ROUTE:'En route',ANNULEE:'Annulée',ACTIVE:'Active',APPROUVEE:'Approuvée',PROSPECT:'Prospect',SUSPENDUE:'Suspendue'};
function label(t){return LABELS[t]||t;}
/* Finalisation 2027 : depuis chaque résultat, un lien ouvre l'écran métier correspondant. */
function links(x){var d=x.details||{},e=encodeURIComponent,L=[];
 if(d.producteur_id)L.push(['field-buying.html#farmers/'+e(d.producteur_id),'Farmer Passport']);
 if(d.cooperative_id)L.push(['field-buying.html#cooperatives/'+e(d.cooperative_id)+'/overview','Fiche coopérative']);
 if(x.entity_type==='RT'&&d.rt_id)L.push(['field-buying.html#rt/'+e(d.rt_id),'Fiche RT']);
 if(x.entity_type==='WMS_LOT'||d.lot_id)L.push(['warehouse.html#lots','LOT au Warehouse']);
 if(x.entity_type==='WMS_RECEPTION'||d.reception)L.push(['warehouse.html#receptions','Réceptions Warehouse']);
 if(x.entity_type==='WMS_TRANSFER')L.push(['stock-transfer.html#transfers','Transfert']);
 if(x.entity_type==='WMS_TRANSFER'&&d.dest_is_factory)L.push(['factory.html#reception','Réception usine']);
 if(x.entity_type==='PROCUREMENT_ARRIVAL'||x.entity_type==='COOP_DELIVERY')L.push(['procurement.html#arrivals','Arrivages prévus']);
 return L.length?'<div class="ops-actions" style="justify-content:flex-start;margin-top:8px">'+L.map(function(l){return '<a class="btn secondary" href="'+l[0]+'">'+esc(l[1])+' →</a>';}).join('')+'</div>':'';}
function step(title,value,sub){return '<div class="kpi"><small>'+esc(title)+'</small><b>'+value+'</b><span>'+esc(sub||'')+'</span></div>';}
function coopChain(id,box){waitClient().then(function(sb){return sb.rpc('aflp_coop_chain',{p_coop:id,p_campaign:'2027'});}).then(function(r){if(r.error)throw r.error;var c=r.data||{},p=c.producteurs||{},a=c.achats_mode_a||{},fl=c.achats_vers_lots_terrain||{},d=c.livraisons||[],l=c.lots||[];
 var bins=[],trf=[],fac=0;l.forEach(function(x){(x.bins||[]).forEach(function(b){if(bins.indexOf(b)<0)bins.push(b);});(x.transferts||[]).forEach(function(t){trf.push(t);if(t.usine)fac++;});});
 box.innerHTML='<p class="muted" style="font-size:11px;margin:8px 0">Coopérative → Producteurs → Achats → Livraisons → Lots → Warehouse → Transfers → Factory</p><section class="kpi-grid">'+
 step('Producteurs',String(p.ouverts||0),(p.verifies||0)+' vérifiés · '+(p.historique||0)+' affiliations')+step('Achats membres',mt(a.kg),(a.nombre||0)+' achat(s)')+step('Lots terrain',String(fl.lots||0),mt(fl.kg))+
 step('Livraisons',String(d.length),d.filter(function(x){return x.allocation==='ALLOCATION_A_COMPLETER';}).length+' à répartir')+step('Lots Warehouse',String(l.length),bins.length+' BIN')+step('Transfers / Factory',String(trf.length),fac+' vers usine')+'</section>'+
 (l.length?'<div class="table-wrap"><table><thead><tr><th>LOT</th><th>Réception</th><th>Poids</th><th>Canal</th><th>Producteurs</th><th>BIN</th><th>Traçabilité</th></tr></thead><tbody>'+l.map(function(x){return '<tr><td class="mono">'+esc(x.lot)+'</td><td class="mono">'+esc(x.reception||'—')+'</td><td>'+fmtKg(x.kg)+'</td><td>'+esc(VALUES[x.canal]||x.canal)+'</td><td>'+esc(x.producteurs)+'</td><td class="mono">'+esc((x.bins||[]).join(', ')||'—')+'</td><td>'+esc(VALUES[x.tracabilite]||x.tracabilite)+'</td></tr>';}).join('')+'</tbody></table></div>':'')+
 '<div class="ops-actions" style="justify-content:flex-start;margin-top:8px"><a class="btn secondary" href="field-buying.html#cooperatives/'+encodeURIComponent(id)+'/purchases">Ouvrir la fiche coopérative →</a></div>';
}).catch(function(e){box.innerHTML='<div class="notice danger">'+esc(e&&e.message?e.message:e)+'</div>';});}
async function search(q){var out=document.getElementById('traceResults');if(!out)return;q=String(q||'').trim();if(q.length<2){out.innerHTML='<div class="empty">Saisissez au moins 2 caractères.</div>';return;}out.innerHTML='<div class="empty">Recherche transverse…</div>';var sb=await waitClient();if(!sb){out.innerHTML='<div class="empty">Données indisponibles.</div>';return;}var qq=q.replace(/[%_]/g,'').trim(),dg=qq.replace(/\D/g,'');if(dg.length>=8&&/^[\d\s.+()-]+$/.test(qq)){qq=dg.length>10&&dg.indexOf('225')===0?dg.slice(-10):dg;}
 var r=await sb.from('operations_traceability_search_v').select('*').ilike('search_text','%'+qq+'%').limit(80);if(r.error){out.innerHTML='<div class="notice danger">Recherche impossible : '+esc(r.error.message)+'</div>';return;}var rows=r.data||[];if(!rows.length){out.innerHTML='<div class="empty">Aucun résultat pour « '+esc(q)+' ».</div>';return;}
 rows.sort(function(a,b){var o={FARMER:0,COOPERATIVE:1,COOP_MEMBER:2,PURCHASE:3,RT:4,COOP_DELIVERY:5,PROCUREMENT_ARRIVAL:6,WMS_RECEPTION:7,WMS_LOT:8,WMS_BIN:9,WMS_TRANSFER:10};return (o[a.entity_type]==null?9:o[a.entity_type])-(o[b.entity_type]==null?9:o[b.entity_type]);});
 out.innerHTML=rows.map(function(x,i){var d=x.details||{};var meta=[];if(x.origin_label||x.destination_label)meta.push(esc(x.origin_label||'—')+' → '+esc(x.destination_label||'—'));if(x.qty_kg!=null)meta.push(fmtKg(x.qty_kg));if(x.event_date)meta.push(esc(x.event_date));
  var title=x.entity_type==='COOPERATIVE'?esc(x.entity_id)+' · '+esc(d.name||''):esc(x.entity_id||'Résultat');
  return '<article class="card" style="margin-bottom:10px"><div class="card-head"><div><h3>'+title+'</h3><p>'+esc(label(x.entity_type))+'</p></div><span class="badge '+(x.entity_type==='COOPERATIVE'||x.entity_type==='COOP_DELIVERY'?'ok':'info')+'">'+esc(label(x.entity_type))+'</span></div>'+(meta.length?'<p class="muted" style="font-size:11px">'+meta.join(' · ')+'</p>':'')+
  '<div class="table-wrap"><table style="min-width:0"><tbody>'+Object.keys(d).filter(function(k){return d[k]!=null&&d[k]!==''&&k!=='cooperative_id';}).slice(0,12).map(function(k){var v=d[k];return '<tr><th style="width:180px">'+esc(KEYS[k]||k.replaceAll('_',' '))+'</th><td>'+esc(typeof v==='object'?JSON.stringify(v):(VALUES[v]||v))+'</td></tr>';}).join('')+'</tbody></table></div>'+
  links(x)+(x.entity_type==='COOPERATIVE'&&d.cooperative_id?'<div id="coopChain'+i+'" data-coop="'+esc(d.cooperative_id)+'"><div class="skeleton skeleton-row"></div></div>':'')+'</article>';}).join('');
 out.querySelectorAll('[data-coop]').forEach(function(b){coopChain(b.getAttribute('data-coop'),b);});}
function bind(){var f=document.getElementById('traceForm'),i=document.getElementById('traceQuery');if(!f||!i)return;f.addEventListener('submit',function(e){e.preventDefault();e.stopImmediatePropagation();search(i.value);},true);
 var m=/(?:coop|q)=([^&]+)/.exec(location.hash||'');if(m){i.value=decodeURIComponent(m[1]);setTimeout(function(){search(i.value);},300);}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();g.ANAGROCI_TRACE_SEARCH=search;
})(window);
