/* Recherche transverse Traceability 360 — projection SQL, aucune duplication transactionnelle.
   Objets traçables : Farmer, LBA, Funding Cycle, généalogie RCN, transfert, COOPÉRATIVE (AFLP 2027),
   livraison de coopérative et LOT Warehouse avec son origine (canal, coopérative, producteurs). */
(function(g){'use strict';
function esc(v){return String(v==null?'':v).replace(/[&<>\"]/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c];});}
var client=null;
function waitClient(){if(client)return Promise.resolve(client);return new Promise(function(resolve){var n=0,t=setInterval(function(){n++;if(g.supabase&&g.ANAGROCI_SUPABASE_URL&&g.ANAGROCI_SUPABASE_ANON){clearInterval(t);client=g.supabase.createClient(g.ANAGROCI_SUPABASE_URL,g.ANAGROCI_SUPABASE_ANON);resolve(client);}else if(n>100){clearInterval(t);resolve(null);}},80);});}
function fmtKg(v){var n=Number(v||0);return n?new Intl.NumberFormat('fr-FR',{maximumFractionDigits:0}).format(n)+' kg':'—';}
function mt(v){return new Intl.NumberFormat('fr-FR',{maximumFractionDigits:1}).format(Number(v||0)/1000)+' MT';}
var LABELS={FARMER_CHAIN:'Farmer / Field',RCN_GENEALOGY:'RCN Genealogy',LBA:'LBA',FUNDING_CYCLE:'Funding Cycle',STOCK_TRANSFER:'Stock Transfer',COOPERATIVE:'Coopérative AFLP',COOP_DELIVERY:'Livraison coopérative',WMS_LOT:'LOT Warehouse'};
var KEYS={origin_channel:'Canal d’origine',cooperatives:'Coopérative(s)',farmers:'Producteurs',villages:'Villages',traceability:'Traçabilité',reception:'Réception',status:'Statut',cooperative:'Coopérative',allocation:'Répartition producteurs',allocated_kg:'Alloué (kg)',arrival:'Arrivage',name:'Nom',cluster:'Cluster',locality:'Localité'};
var VALUES={COOPERATIVE:'Coopérative',AFLP_DIRECT:'Direct RT',MIXTE:'Mixte',TRACABLE_PRODUCTEUR:'Traçable producteur',ALLOCATION_A_COMPLETER:'Allocation à compléter',ORGANISATION_SEULEMENT:'Organisation seulement',TRACABLE:'Traçable producteur',ALLOUEE_PREVISION:'Allouée (prévision)',PLANIFIEE:'Planifiée',RECUE:'Reçue',EN_ROUTE:'En route',ANNULEE:'Annulée',ACTIVE:'Active',APPROUVEE:'Approuvée',PROSPECT:'Prospect',SUSPENDUE:'Suspendue'};
function label(t){return LABELS[t]||t;}
function step(title,value,sub){return '<div class="kpi"><small>'+esc(title)+'</small><b>'+value+'</b><span>'+esc(sub||'')+'</span></div>';}
function coopChain(id,box){waitClient().then(function(sb){return sb.rpc('aflp_coop_chain',{p_coop:id,p_campaign:'2027'});}).then(function(r){if(r.error)throw r.error;var c=r.data||{},p=c.producteurs||{},a=c.achats_mode_a||{},fl=c.achats_vers_lots_terrain||{},d=c.livraisons||[],l=c.lots||[];
 var bins=[],trf=[],fac=0;l.forEach(function(x){(x.bins||[]).forEach(function(b){if(bins.indexOf(b)<0)bins.push(b);});(x.transferts||[]).forEach(function(t){trf.push(t);if(t.usine)fac++;});});
 box.innerHTML='<p class="muted" style="font-size:11px;margin:8px 0">Coopérative → Producteurs → Achats → Livraisons → Lots → Warehouse → Transfers → Factory</p><section class="kpi-grid">'+
 step('Producteurs',String(p.ouverts||0),(p.verifies||0)+' vérifiés · '+(p.historique||0)+' affiliations')+step('Achats membres',mt(a.kg),(a.nombre||0)+' achat(s)')+step('Lots terrain',String(fl.lots||0),mt(fl.kg))+
 step('Livraisons',String(d.length),d.filter(function(x){return x.allocation==='ALLOCATION_A_COMPLETER';}).length+' à répartir')+step('Lots Warehouse',String(l.length),bins.length+' BIN')+step('Transfers / Factory',String(trf.length),fac+' vers usine')+'</section>'+
 (l.length?'<div class="table-wrap"><table><thead><tr><th>LOT</th><th>Réception</th><th>Poids</th><th>Canal</th><th>Producteurs</th><th>BIN</th><th>Traçabilité</th></tr></thead><tbody>'+l.map(function(x){return '<tr><td class="mono">'+esc(x.lot)+'</td><td class="mono">'+esc(x.reception||'—')+'</td><td>'+fmtKg(x.kg)+'</td><td>'+esc(VALUES[x.canal]||x.canal)+'</td><td>'+esc(x.producteurs)+'</td><td class="mono">'+esc((x.bins||[]).join(', ')||'—')+'</td><td>'+esc(VALUES[x.tracabilite]||x.tracabilite)+'</td></tr>';}).join('')+'</tbody></table></div>':'')+
 '<div class="ops-actions" style="justify-content:flex-start;margin-top:8px"><a class="btn secondary" href="field-buying.html#cooperatives/'+encodeURIComponent(id)+'/purchases">Ouvrir la fiche coopérative →</a></div>';
}).catch(function(e){box.innerHTML='<div class="notice danger">'+esc(e&&e.message?e.message:e)+'</div>';});}
async function search(q){var out=document.getElementById('traceResults');if(!out)return;q=String(q||'').trim();if(q.length<2){out.innerHTML='<div class="empty">Saisissez au moins 2 caractères.</div>';return;}out.innerHTML='<div class="empty">Recherche transverse…</div>';var sb=await waitClient();if(!sb){out.innerHTML='<div class="empty">Données indisponibles.</div>';return;}var r=await sb.from('operations_traceability_search_v').select('*').ilike('search_text','%'+q.replace(/[%_]/g,'')+'%').limit(80);if(r.error){out.innerHTML='<div class="notice danger">Recherche impossible : '+esc(r.error.message)+'</div>';return;}var rows=r.data||[];if(!rows.length){out.innerHTML='<div class="empty">Aucun résultat pour « '+esc(q)+' ».</div>';return;}
 rows.sort(function(a,b){var o={COOPERATIVE:0,COOP_DELIVERY:1,WMS_LOT:2};return (o[a.entity_type]==null?9:o[a.entity_type])-(o[b.entity_type]==null?9:o[b.entity_type]);});
 out.innerHTML=rows.map(function(x,i){var d=x.details||{};var meta=[];if(x.origin_label||x.destination_label)meta.push(esc(x.origin_label||'—')+' → '+esc(x.destination_label||'—'));if(x.qty_kg!=null)meta.push(fmtKg(x.qty_kg));if(x.event_date)meta.push(esc(x.event_date));
  var title=x.entity_type==='COOPERATIVE'?esc(x.entity_id)+' · '+esc(d.name||''):esc(x.entity_id||'Résultat');
  return '<article class="card" style="margin-bottom:10px"><div class="card-head"><div><h3>'+title+'</h3><p>'+esc(label(x.entity_type))+'</p></div><span class="badge '+(x.entity_type==='COOPERATIVE'||x.entity_type==='COOP_DELIVERY'?'ok':'info')+'">'+esc(label(x.entity_type))+'</span></div>'+(meta.length?'<p class="muted" style="font-size:11px">'+meta.join(' · ')+'</p>':'')+
  '<div class="table-wrap"><table style="min-width:0"><tbody>'+Object.keys(d).filter(function(k){return d[k]!=null&&d[k]!==''&&k!=='cooperative_id';}).slice(0,12).map(function(k){var v=d[k];return '<tr><th style="width:180px">'+esc(KEYS[k]||k.replaceAll('_',' '))+'</th><td>'+esc(typeof v==='object'?JSON.stringify(v):(VALUES[v]||v))+'</td></tr>';}).join('')+'</tbody></table></div>'+
  (x.entity_type==='COOPERATIVE'&&d.cooperative_id?'<div id="coopChain'+i+'" data-coop="'+esc(d.cooperative_id)+'"><div class="skeleton skeleton-row"></div></div>':'')+'</article>';}).join('');
 out.querySelectorAll('[data-coop]').forEach(function(b){coopChain(b.getAttribute('data-coop'),b);});}
function bind(){var f=document.getElementById('traceForm'),i=document.getElementById('traceQuery');if(!f||!i)return;f.addEventListener('submit',function(e){e.preventDefault();e.stopImmediatePropagation();search(i.value);},true);
 var m=/(?:coop|q)=([^&]+)/.exec(location.hash||'');if(m){i.value=decodeURIComponent(m[1]);setTimeout(function(){search(i.value);},300);}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();g.ANAGROCI_TRACE_SEARCH=search;
})(window);
