/* Recherche transverse Traceability 360 — projection SQL, aucune duplication transactionnelle. */
(function(g){'use strict';
function esc(v){return String(v==null?'':v).replace(/[&<>\"]/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c];});}
function waitClient(){return new Promise(function(resolve){var n=0,t=setInterval(function(){n++;if(g.supabase&&g.ANAGROCI_SUPABASE_URL&&g.ANAGROCI_SUPABASE_ANON){clearInterval(t);resolve(g.supabase.createClient(g.ANAGROCI_SUPABASE_URL,g.ANAGROCI_SUPABASE_ANON));}else if(n>100){clearInterval(t);resolve(null);}},80);});}
function fmtKg(v){var n=Number(v||0);return n?new Intl.NumberFormat('fr-FR',{maximumFractionDigits:0}).format(n)+' kg':'—';}
function label(t){return {FARMER_CHAIN:'Farmer / Field',RCN_GENEALOGY:'RCN Genealogy',LBA:'LBA',FUNDING_CYCLE:'Funding Cycle',STOCK_TRANSFER:'Stock Transfer'}[t]||t;}
async function search(q){var out=document.getElementById('traceResults');if(!out)return;q=String(q||'').trim();if(q.length<2){out.innerHTML='<div class="empty">Saisissez au moins 2 caractères.</div>';return;}out.innerHTML='<div class="empty">Recherche transverse…</div>';var sb=await waitClient();if(!sb){out.innerHTML='<div class="empty">Supabase indisponible.</div>';return;}var r=await sb.from('operations_traceability_search_v').select('*').ilike('search_text','%'+q.replace(/[%_]/g,'')+'%').limit(80);if(r.error){out.innerHTML='<div class="notice danger">Recherche impossible : '+esc(r.error.message)+'</div>';return;}var rows=r.data||[];if(!rows.length){out.innerHTML='<div class="empty">Aucun résultat pour « '+esc(q)+' ».</div>';return;}out.innerHTML=rows.map(function(x){var d=x.details||{};var meta=[];if(x.origin_label||x.destination_label)meta.push(esc(x.origin_label||'—')+' → '+esc(x.destination_label||'—'));if(x.qty_kg!=null)meta.push(fmtKg(x.qty_kg));if(x.event_date)meta.push(esc(x.event_date));return '<article class="card" style="margin-bottom:10px"><div class="card-head"><div><h3>'+esc(x.entity_id||'Résultat')+'</h3><p>'+esc(label(x.entity_type))+'</p></div><span class="badge info">'+esc(x.entity_type)+'</span></div>'+(meta.length?'<p class="muted" style="font-size:11px">'+meta.join(' · ')+'</p>':'')+'<div class="table-wrap"><table style="min-width:0"><tbody>'+Object.keys(d).filter(function(k){return d[k]!=null&&d[k]!=='';}).slice(0,12).map(function(k){return '<tr><th style="width:180px">'+esc(k.replaceAll('_',' '))+'</th><td>'+esc(typeof d[k]==='object'?JSON.stringify(d[k]):d[k])+'</td></tr>';}).join('')+'</tbody></table></div></article>';}).join('');}
function bind(){var f=document.getElementById('traceForm'),i=document.getElementById('traceQuery');if(!f||!i)return;f.addEventListener('submit',function(e){e.preventDefault();e.stopImmediatePropagation();search(i.value);},true);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();g.ANAGROCI_TRACE_SEARCH=search;
})(window);