/* ANAGROCI FR/EN interface switch */
(function(){
  "use strict";
  var KEY="anagroci_lang",busy=false,timer=null;
  var originals=new WeakMap(), attrOriginals=new WeakMap();
  var D={
"Vérification de l'accès…":"Checking access...","Accès sécurisé":"Secure access","Mot de passe":"Password","Se connecter":"Sign in","Connexion…":"Signing in...","Email ou mot de passe incorrect.":"Incorrect email or password.","Pas encore d'accès ? Le Branch Manager crée votre compte et vous attribue vos droits.":"No access yet? The Branch Manager creates your account and assigns your permissions.","Accès non autorisé":"Access not authorized","Retour au portail":"Back to portal","Se déconnecter":"Sign out","Profil introuvable. Contactez le Branch Manager.":"Profile not found. Contact the Branch Manager.","Compte désactivé. Contactez le Branch Manager.":"Account disabled. Contact the Branch Manager.","Connexion requise (aucun profil en cache pour le mode hors-ligne).":"Sign-in required (no cached profile for offline mode).",
"Plateforme en ligne":"Platform online","Le poste de commande terrain d'ANAGROCI":"ANAGROCI field command center","Référentiel maître FBMS, cartographie, audit des distances et logistique ALIS — réunis dans un portail unique, gouverné par une donnée partagée.":"FBMS master data, mapping, distance audit and ALIS logistics — brought together in one portal governed by shared data.","Pilotage":"Management","Priorité 1":"Priority 1","Priorité 2":"Priority 2","Priorité 3":"Priority 3","Prioritaire":"Priority","Actif":"Active","Officiel":"Official","Ouvrir le module":"Open module","Tableau de bord Branch Manager : volume acheté, cash engagé, sacs, anomalies du jour et vue par cluster.":"Branch Manager dashboard: purchased volume, cash committed, bags, daily anomalies and cluster view.","Achats Terrain":"Field Purchases","Saisie journalière des achats RCN (Producteur → RT), hors-ligne : poids, prix, reçu, commission RT, synchro automatique.":"Daily RCN purchase entry (Producer to RT), offline: weight, price, receipt, RT commission, automatic sync.","Caisse & Avances":"Cash & Advances","Cash Control : avances RT, solde (avance − achats), réconciliation quotidienne et blocage du refinancement.":"Cash Control: RT advances, balance, daily reconciliation and refinancing block.","Stock & Sacs":"Stock & Bags","FBMS Référentiel":"FBMS Master Data","Le référentiel maître : zones, clusters, villages, RT et producteurs. Ouvre FBMS avec retour portail.":"Master data: zones, clusters, villages, RTs and producers. Opens FBMS with portal return.","Cartographie Terrain":"Field Mapping","Villages, hubs, axes routiers et distances visualisés sur une carte interactive.":"Villages, hubs, road routes and distances shown on an interactive map.","Audit Distances":"Distance Audit","Validation des distances routières et contrôle GPS avant tout calcul logistique.":"Road-distance validation and GPS control before any logistics calculation.","ALIS Depuis FBMS":"ALIS From FBMS","Module logistique officiel : coût rendu usine, tarifs et barème collecte courte modifiables.":"Official logistics module: delivered factory cost, rates and editable short-collection scale.","Une donnée, une identité, une plateforme.":"One data set, one identity, one platform.",
"Portail":"Portal","Actualiser":"Refresh","Chargement…":"Loading...","Volume acheté":"Purchased volume","objectif 11 000 MT":"target 11,000 MT","Cash engagé (avances)":"Cash committed (advances)","Sacs en main (RT)":"Bags on hand (RT)","Prix moyen producteur":"Average producer price","À faire aujourd'hui · anomalies":"Today's actions / anomalies","Terrain":"Field","Par cluster":"By cluster","Cluster":"Cluster","Villages":"Villages","Volume (MT)":"Volume (MT)","Avancé":"Advanced","Solde":"Balance","Sacs entrepôt":"Warehouse bags","RT à risque (écart caisse / sacs)":"RTs at risk (cash / bag variance)","Solde caisse":"Cash balance","Réconciliation":"Reconciliation","Sacs en main":"Bags on hand",
"Saisie journalière RCN · Producteur → RT":"Daily RCN entry · Producer to RT","Hors ligne":"Offline","En ligne":"Online","Synchroniser":"Sync","Volume du jour":"Today's volume","Montant payé (jour)":"Amount paid (today)","Commission RT (jour)":"RT commission (today)","En attente de synchro":"Pending sync","Nouvel achat":"New purchase","Date":"Date","Tous les clusters":"All clusters","Village":"Village","Choisir ou saisir":"Select or enter","RT (équipe)":"RT (team)","Producteur":"Producer","Nom ou code":"Name or code","Poids brut (kg)":"Gross weight (kg)","Tare (kg)":"Tare (kg)","Poids net (kg)":"Net weight (kg)","Prix / kg (barème 400)":"Price / kg (400 scale)","Montant payé":"Amount paid","Nb sacs":"No. of bags","Mode de paiement":"Payment method","Espèces":"Cash","Virement":"Bank transfer","Autre":"Other","N° reçu":"Receipt No.","Requis pour refinancement":"Required for refinancing","Humidité %":"Moisture %","Rejet":"Rejection","Non":"No","Oui (partiel/total)":"Yes (partial/total)","Observation":"Notes","Facultatif":"Optional","Photo du reçu (facultatif)":"Receipt photo (optional)","Commission RT : 0 FCFA":"RT commission: 0 FCFA","Bonus différé : 0 FCFA":"Deferred bonus: 0 FCFA","Sans reçu → non refinançable":"No receipt: not eligible for refinancing","Qualité : à contrôler":"Quality: to be checked","Prix hors barème → validation BM":"Price outside scale: BM approval","Enregistrer l'achat":"Save purchase","Derniers achats":"Latest purchases","Référentiel non chargé. Connectez-vous une fois en ligne pour charger villages / RT / producteurs.":"Master data not loaded. Sign in once online to load villages, RTs and producers.","Aucun achat saisi sur cet appareil.":"No purchase entered on this device.","Synchronisé":"Synced","En attente":"Pending","Non refinançable":"Not eligible for refinancing","À valider":"To validate","Validation BM requise":"BM approval required","À contrôler":"To be checked","Rejeté":"Rejected","Village requis.":"Village is required.","RT requis : un achat doit être rattaché à une équipe RT.":"RT is required: a purchase must be attached to an RT team.","Poids net invalide (brut − tare doit être > 0).":"Invalid net weight (gross minus tare must be above 0).","Prix / kg invalide.":"Invalid price per kg.","Nombre de sacs requis (au moins 1) pour un achat avec poids.":"Number of bags required (at least 1) for a purchase with weight.","Achat enregistré":"Purchase saved","Producteur non référencé — à régulariser.":"Producer not in master data - to regularize.","Reçu saisi → refinançable":"Receipt entered: eligible for refinancing","Lot rejeté → non refinançable":"Rejected lot: not eligible for refinancing",
"Caisse":"Cash desk","Avances":"Advances","Nouvelle avance":"New advance","Montant":"Amount","Motif":"Reason","Bénéficiaire":"Beneficiary","Réconcilier":"Reconcile","Mouvement de sacs":"Bag movement","Dotation RT":"RT allocation","Distribution producteur":"Producer distribution","Retour":"Return","Déchirés":"Damaged","Source":"Source","Destination":"Destination","Quantité":"Quantity","Enregistrer":"Save","Historique":"History","Référentiel":"Master Data","Zones":"Zones","Clusters":"Clusters","Producteurs":"Producers","Fermiers":"Farmers","Ajouter":"Add","Modifier":"Edit","Supprimer":"Delete","Exporter":"Export","Importer":"Import","Rechercher":"Search","Filtrer":"Filter","Nom":"Name","Prénom":"First name","Téléphone":"Phone","Région":"Region","Département":"Department","Sous-préfecture":"Sub-prefecture","Distance":"Distance","GPS":"GPS","Statut":"Status","Potentiel":"Potential","Concurrence":"Competition","Risque":"Risk","Accès":"Access","Route":"Road","Annuler":"Cancel","Fermer":"Close","Valider":"Validate","Validation":"Validation","Carte":"Map","Liste":"List","Localiser":"Locate","Audit":"Audit","Écart":"Variance","Anomalies":"Anomalies","Logistique":"Logistics","Transport":"Transport","Tarifs":"Rates","Barème":"Scale","Coût rendu usine":"Delivered factory cost","Collecte courte":"Short collection","Calculer":"Calculate","Résultat":"Result","Paramètres":"Settings","Administration":"Administration","Utilisateurs":"Users","Droits":"Permissions","Rôle":"Role","Compte":"Account","Langue":"Language","Français":"French","Anglais":"English"};
  var P=[["À contrôler","To be checked"],["À valider","To validate"],["Validation BM requise","BM approval required"],["Rejeté","Rejected"],["Synchronisé","Synced"],["En attente","Pending"],["Non refinançable","Not eligible for refinancing"],["qualité","quality"],["producteur à régulariser","producer to regularize"],["producteur ?","producer?"],["reçu","receipt"]];
  function getLang(){return localStorage.getItem(KEY)==="en"?"en":"fr"}
  function clean(s){return String(s||"").replace(/\u00a0/g," ").replace(/\s+/g," ").trim()}
  function tr(s){if(getLang()!=="en")return s;var a=String(s),lead=(a.match(/^\s*/)||[""])[0],tail=(a.match(/\s*$/)||[""])[0],x=clean(a);if(!x)return s;if(D[x])return lead+D[x]+tail;var out=x;P.forEach(function(p){out=out.split(p[0]).join(p[1])});out=out.replace(/^Commission RT\s*:\s*/i,"RT commission: ").replace(/^Bonus différé\s*:\s*/i,"Deferred bonus: ").replace(/^Qualité\s*:\s*/i,"Quality: ").replace(/^Statut\s*:\s*/i,"Status: ");return lead+out+tail}
  function skip(n){var e=n.nodeType===3?n.parentElement:n;return !e||e.closest("script,style,noscript,svg,[data-i18n-ignore]")}
  function eachText(root,fn){var w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode:function(n){return skip(n)||!clean(n.nodeValue)?NodeFilter.FILTER_REJECT:NodeFilter.FILTER_ACCEPT}}),n;while((n=w.nextNode()))fn(n)}
  function amap(e){var m=attrOriginals.get(e);if(!m){m={};attrOriginals.set(e,m)}return m}
  function apply(){if(!document.body||busy)return;busy=true;var L=getLang();document.documentElement.lang=L;eachText(document.body,function(n){var src=originals.get(n),cur=n.nodeValue;if(L==="en"){if(!src||(cur!==src&&cur!==tr(src)))src=cur;originals.set(n,src);n.nodeValue=tr(src)}else if(src)n.nodeValue=src});document.querySelectorAll("[placeholder],[title],[aria-label],input[type=button],input[type=submit],button").forEach(function(e){var m=amap(e);["placeholder","title","aria-label"].forEach(function(a){if(!e.hasAttribute(a))return;var cur=e.getAttribute(a),src=m[a];if(L==="en"){if(!src||(cur!==src&&cur!==tr(src)))src=cur;m[a]=src;e.setAttribute(a,tr(src))}else if(src)e.setAttribute(a,src)});if((e.tagName==="INPUT"||e.tagName==="BUTTON")&&e.value){var v=e.value,sv=m.value;if(L==="en"){if(!sv||(v!==sv&&v!==tr(sv)))sv=v;m.value=sv;e.value=tr(sv)}else if(sv)e.value=sv}});toggle();busy=false}
  function schedule(){clearTimeout(timer);timer=setTimeout(apply,60)}
  function toggle(){var b=document.getElementById("anagroci-lang-toggle");if(!b){b=document.createElement("div");b.id="anagroci-lang-toggle";b.innerHTML='<button type="button" data-l="fr">FR</button><button type="button" data-l="en">EN</button>';document.body.appendChild(b);b.onclick=function(e){var l=e.target&&e.target.getAttribute("data-l");if(l){localStorage.setItem(KEY,l);apply()}}}b.querySelectorAll("button").forEach(function(x){x.className=x.getAttribute("data-l")===getLang()?"on":""})}
  function css(){if(document.getElementById("anagroci-i18n-css"))return;var s=document.createElement("style");s.id="anagroci-i18n-css";s.textContent='#anagroci-lang-toggle{position:fixed;left:12px;top:12px;z-index:2147483001;display:flex;gap:3px;background:rgba(5,59,35,.92);border:1px solid rgba(255,255,255,.18);border-radius:999px;padding:4px;box-shadow:0 8px 22px rgba(0,0,0,.22)}#anagroci-lang-toggle button{border:0;border-radius:999px;background:transparent;color:#eafff2;font:800 11px Segoe UI,Arial,sans-serif;padding:6px 8px;cursor:pointer}#anagroci-lang-toggle button.on{background:#8DC556;color:#053B23}@media(max-width:560px){#anagroci-lang-toggle{top:auto;bottom:12px}}';document.head.appendChild(s)}
  function init(){css();apply();new MutationObserver(function(){if(!busy)schedule()}).observe(document.body,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:["placeholder","title","aria-label","value"]});document.addEventListener("anagroci:authenticated",schedule);window.ANAGROCI_I18N={set:function(l){localStorage.setItem(KEY,l==="en"?"en":"fr");apply()},get:getLang,t:tr,apply:apply}}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();
