/* ANAGROCI FR/EN extra translations - non destructive */
(function(){
  'use strict';
  var KEY='anagroci_lang', busy=false, timer=null;
  var originals=new WeakMap(), attrOriginals=new WeakMap();
  var D={
    'Total avancé':'Total advanced','Total payé (achats)':'Total paid for purchases','Solde global':'Global balance','RT à contrôler':'RTs to check','Montant (FCFA)':'Amount (XOF)','Enregistrer l\'avance':'Save advance','RT à réconcilier':'RT to reconcile','Payé (achats)':'Paid for purchases','Cash restant déclaré':'Declared cash remaining','Valeur stock estimée':'Estimated stock value','Écart : — · statut : —':'Variance: — · status: —','Soldes par RT':'Balances by RT','Réconcilié':'Reconciled','Finance':'Finance','Cluster Head':'Cluster Head',
    'Dotation RT · distribution producteurs · enlèvement':'RT allocation · farmer distribution · pickup','Sacs distribués':'Bags distributed','Sacs pleins ramassés':'Full bags collected','Sacs en main (RT)':'Bags held by RTs','Sacs déchirés':'Torn bags','Nouveau mouvement':'New movement','Nouveau mouvement de sacs':'New bag movement','Flux : —':'Flow: —','Type de mouvement':'Movement type','Producteur enrôlé':'Enrolled farmer','Nombre de sacs':'Number of bags','Document de transaction (scan)':'Transaction document scan','Enregistrer le mouvement':'Save movement','Soldes sacs':'Bag balances','Entrepôts':'Warehouses','RT (équipes)':'RT teams','Sacs en entrepôt':'Bags in warehouse','Historique des mouvements':'Movement history','mouvement':'movement','mouvements':'movements','Du':'From','Au':'To','Tous les types':'All types','Acteur':'Actor','Tous les acteurs':'All actors','Tous les villages':'All villages','Réinitialiser':'Reset','Acteur · village':'Actor · village','État':'Status','Aucun mouvement.':'No movement.',
    'Réception cluster (Usine → Cluster)':'Cluster receipt (Factory → Cluster)','Dotation RT (Cluster → RT)':'RT allocation (Cluster → RT)','Distribution (RT → producteur)':'Distribution (RT → farmer)','Enlèvement (sacs pleins ramassés)':'Pickup (full bags collected)','Retour vides (producteur → RT)':'Empty bag return (farmer → RT)','Retour vides (RT → Cluster)':'Empty bag return (RT → Cluster)','Sacs déchirés (RT)':'Torn bags (RT)','Sacs déchirés (producteur)':'Torn bags (farmer)','USINE':'FACTORY','PRODUCTEUR':'FARMER','PERTE':'LOSS',
    'Scanner le document de transaction':'Scan transaction document','Autorisez l\'accès à la caméra…':'Allow camera access...','Autorisez l’accès à la caméra…':'Allow camera access...','Choisissez un fichier image.':'Choose an image file.','Image illisible.':'Image unreadable.','Document de transaction':'Transaction document','Télécharger':'Download','Aucun':'None','Agrandir':'Enlarge','Importer':'Import','Document de transaction (scan)':'Transaction document scan',
    'Total avancé':'Total advanced','Total payé':'Total paid','Cash Control · avance → paiement → réconciliation':'Cash Control · advance → payment → reconciliation','Nouvelle avance':'New advance','Tous les clusters':'All clusters','Choisir ou saisir':'Select or enter','Facultatif':'Optional','Enregistrer la réconciliation':'Save reconciliation','Soldes':'Balances','Historique':'History','Sacs en main':'Bags on hand','Sacs en main (RT)':'Bags held by RTs','Sacs pleins ramassés':'Full bags collected','Sacs déchirés':'Torn bags','Sacs déchirés (producteur)':'Torn bags (farmer)','Sacs déchirés (RT)':'Torn bags (RT)','Nouveau mouvement':'New movement','Soldes sacs':'Bag balances','Aucun mouvement RT.':'No RT movement.','Aucun mouvement producteur.':'No farmer movement.','Aucun mouvement pour ce filtre.':'No movement for this filter.','Aucune réception cluster.':'No cluster receipt.','Nombre de sacs invalide.':'Invalid number of bags.','RT requis pour ce mouvement.':'RT is required for this movement.','Producteur requis pour ce mouvement.':'Farmer is required for this movement.','Mouvement enregistré':'Movement saved','hors ligne':'offline'
  };
  function lang(){return localStorage.getItem(KEY)==='en'?'en':'fr'}
  function clean(s){return String(s==null?'':s).replace(/\u00a0/g,' ').replace(/\s+/g,' ').trim()}
  function keys(){return Object.keys(D).sort(function(a,b){return b.length-a.length})}
  var sorted=null;
  function tr(s){if(lang()!=='en')return s;var a=String(s==null?'':s),lead=(a.match(/^\s*/)||[''])[0],tail=(a.match(/\s*$/)||[''])[0],x=clean(a);if(!x)return s;if(D[x])return lead+D[x]+tail;var out=x;(sorted||(sorted=keys())).forEach(function(k){if(k.length>2&&out.indexOf(k)>=0)out=out.split(k).join(D[k])});return lead+out+tail}
  function skip(n){var e=n.nodeType===3?n.parentElement:n;return !e||e.closest('script,style,noscript,svg,[data-i18n-ignore]')}
  function each(root,fn){var w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode:function(n){return skip(n)||!clean(n.nodeValue)?NodeFilter.FILTER_REJECT:NodeFilter.FILTER_ACCEPT}}),n;while((n=w.nextNode()))fn(n)}
  function amap(e){var m=attrOriginals.get(e);if(!m){m={};attrOriginals.set(e,m)}return m}
  function apply(){if(!document.body||busy)return;busy=true;var L=lang();each(document.body,function(n){var src=originals.get(n),cur=n.nodeValue;if(L==='en'){if(!src||(cur!==src&&cur!==tr(src)))src=cur;originals.set(n,src);n.nodeValue=tr(src)}else if(src){n.nodeValue=src}});document.querySelectorAll('[placeholder],[title],[aria-label],input[type=button],input[type=submit],button,option').forEach(function(e){var m=amap(e);['placeholder','title','aria-label'].forEach(function(a){if(!e.hasAttribute(a))return;var cur=e.getAttribute(a),src=m[a];if(L==='en'){if(!src||(cur!==src&&cur!==tr(src)))src=cur;m[a]=src;e.setAttribute(a,tr(src))}else if(src)e.setAttribute(a,src)});if((e.tagName==='INPUT'||e.tagName==='BUTTON'||e.tagName==='OPTION')&&e.textContent){var v=e.textContent,sv=m.text;if(L==='en'){if(!sv||(v!==sv&&v!==tr(sv)))sv=v;m.text=sv;e.textContent=tr(sv)}else if(sv)e.textContent=sv}});busy=false}
  function schedule(){clearTimeout(timer);timer=setTimeout(apply,80)}
  function init(){apply();new MutationObserver(function(){if(!busy)schedule()}).observe(document.body,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['placeholder','title','aria-label','value']});document.addEventListener('anagroci:language',schedule);document.addEventListener('anagroci:authenticated',schedule);window.addEventListener('online',schedule);window.addEventListener('offline',schedule);window.ANAGROCI_I18N_EXTRA={apply:apply,t:tr}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
