/* RCN TRACE — Surcouche UX Sacherie v2. */
(function(g){"use strict";
function E(x){return String(x==null?"":x).replace(/[&<>\"]/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;"}[c];});}
function n(x){return Number(x||0);}
function v(id){var e=document.getElementById(id);return e?e.value:"";}
function toast(s,b){var t=document.getElementById("toast");if(!t){alert(s);return;}t.textContent=s;t.className="toast show"+(b?" err":"");setTimeout(function(){t.className="toast";},3500);}
function locs(){var d=g.RCNJuteControl&&g.RCNJuteControl.data&&g.RCNJuteControl.data();return d&&d.locations||[];}
function locOpts(){return locs().filter(function(x){return x.actif;}).map(function(x){return '<option value="'+E(x.code)+'">'+E(x.code+' · '+x.nom)+'</option>';}).join("");}
function recOpts(){return g.RCNJuteV2.unsynced().map(function(r){return '<option value="'+E(r.id)+'">'+E(r.id+' · '+(r.lba||r.fournisseur||'—')+' · '+n(r.dechargement&&r.dechargement.sacs)+' sacs')+'</option>';}).join("");}
function stateOpts(){return ["UTILISABLE","HUMIDE","DECHIRE","A_REPARER","REPARE","REFORME","A_CLASSER"].map(function(x){return '<option>'+x+'</option>';}).join("");}
function kpi(label,val,sub,cls){return '<div class="kpi '+(cls||'')+'"><small>'+E(label)+'</small><b>'+E(val)+'</b><span>'+E(sub)+'</span></div>';}
function money(x){return new Intl.NumberFormat('fr-FR').format(n(x))+' FCFA';}
function render(){if(location.hash.replace('#','').split('/')[0]!=="sacscontrole")return;var root=document.getElementById("view"),V=g.RCNJuteV2,d=V&&V.data();if(!root||!d)return;if(root.querySelector("#juteV2"))return;var m=V.metrics(),set=d.settings||{},recs=V.unsynced(),profiles=d.profiles||[],purchases=d.purchases||[],transfers=d.transfers||[],repairs=d.repairs||[];
 var path=location.hash.replace('#','').split('/'),supplierCode=path[1]==="fournisseur"?decodeURIComponent(path[2]||''):'';
 var supplierRows=profiles.map(function(x){return '<tr><td><button class="btn ghost sm" onclick="location.hash=\'#sacscontrole/fournisseur/'+encodeURIComponent(x.supplier_code)+'\'">'+E(x.supplier_code)+'</button></td><td>'+n(x.issued)+'</td><td>'+n(x.returned)+'</td><td><b>'+n(x.balance)+'</b></td><td>'+n(x.return_rate).toFixed(1)+' %</td><td>'+n(x.bucket_90_plus)+'</td></tr>';}).join('')||'<tr><td colspan="6" class="empty">Aucune dotation enregistrée.</td></tr>';
 var costPurchase=purchases.reduce(function(t,x){return t+n(x.qty_received)*n(x.unit_price);},0),costRepair=repairs.reduce(function(t,x){return t+n(x.cost);},0);
 var partialP=purchases.filter(function(x){return x.statut==='PARTIEL'||x.statut==='COMMANDE';}).map(function(x){var rest=n(x.qty_ordered)-n(x.qty_received);return '<tr><td>'+E(x.po_ref)+'</td><td>'+E(x.vendor)+'</td><td>'+rest+'</td><td><button class="btn sm" onclick="RCNJuteV2UI.receivePartial(\'ACHAT\',\''+x.id+'\','+rest+')">Recevoir</button></td></tr>';}).join('');
 var partialT=transfers.filter(function(x){return x.statut==='EXPEDIE'||x.statut==='ECART';}).map(function(x){var rest=n(x.qty_sent)-n(x.qty_received);return '<tr><td>'+E(x.document_ref)+'</td><td>'+E(x.from_location+' → '+x.to_location)+'</td><td>'+rest+'</td><td><button class="btn sm" onclick="RCNJuteV2UI.receivePartial(\'TRANSFERT\',\''+x.id+'\','+rest+')">Recevoir</button></td></tr>';}).join('');
 var partialR=repairs.filter(function(x){return x.statut==='ENVOYE'||x.statut==='ECART';}).map(function(x){var rest=n(x.qty_sent)-n(x.qty_repaired)-n(x.qty_irreparable);return '<tr><td>'+E(x.document_ref)+'</td><td>'+E(x.repairer)+'</td><td>'+rest+'</td><td><button class="btn sm" onclick="RCNJuteV2UI.receiveRepair(\''+x.id+'\','+rest+')">Retour</button></td></tr>';}).join('');
 var html='<section id="juteV2" style="margin-bottom:24px">'+
 '<div class="rule" style="margin-bottom:16px"><b>Sacherie sous contrôle.</b> Un retour fournisseur ne modifie plus la balance tant que la propriété et la classification de tous les sacs ne sont pas rapprochées.</div>'+
 '<div class="kpis">'+kpi('Stock utilisable',m.usable,'sacs immédiatement disponibles',m.alert?'danger':'')+kpi('Disponible après besoins',m.free,'prévision : '+m.forecast+' sacs',m.free<m.threshold?'danger':'')+kpi('À rapprocher',m.unsynced,'déchargement(s)','warn')+kpi('Seuil campagne',m.threshold,'alerte automatique','')+'</div>'+
 (m.alert?'<div class="alert"><b>ALERTE SACHERIE :</b> le stock mobilisable après besoins prévus est inférieur à '+m.threshold+' sacs.</div>':'')+
 '<div class="grid2" style="margin-top:18px"><div class="card"><h2>1 · Rapprocher un déchargement <span class="badge b-warn">OBLIGATOIRE</span></h2><div class="cbody">'+
 '<label>Réception à traiter</label><select id="jv_rec" onchange="RCNJuteV2UI.pickReception()"><option value="">Choisir…</option>'+recOpts()+'</select>'+
 '<div class="row"><div><label>Total déchargé</label><input id="jv_total" type="number" readonly></div><div><label>Entrepôt</label><select id="jv_loc">'+locOpts()+'</select></div></div>'+
 '<label>À qui appartiennent les sacs ?</label><div class="row3"><div><label>ANAGROCI</label><input id="jv_company" type="number" min="0" value="0"></div><div><label>Fournisseur</label><input id="jv_supplier" type="number" min="0" value="0"></div><div><label>Inconnus / litige</label><input id="jv_unknown" type="number" min="0" value="0"></div></div>'+
 '<label>Classification des sacs ANAGROCI</label><div class="row3"><div><label>Utilisables</label><input id="jv_usable" type="number" min="0" value="0"></div><div><label>Humides</label><input id="jv_humid" type="number" min="0" value="0"></div><div><label>Déchirés</label><input id="jv_torn" type="number" min="0" value="0"></div></div><div class="row3"><div><label>Déjà réparés</label><input id="jv_repaired" type="number" min="0" value="0"></div><div><label>Autres à classer</label><input id="jv_other" type="number" min="0" value="0"></div><div><label>Référence bon</label><input id="jv_ref"></div></div>'+
 '<div class="row"><div><label>Balles de 500</label><input id="jv_bales" type="number" min="0" value="0"></div><div><label>Sacs en vrac</label><input id="jv_loose" type="number" min="0" value="0"></div></div><label>Photo / bordereau</label><input id="jv_proof" type="file" accept="image/*,.pdf"><label>Observation</label><textarea id="jv_note" rows="2"></textarea><div class="actions"><button class="btn" onclick="RCNJuteV2UI.reconcile()">Vérifier et synchroniser</button></div></div></div>'+
 '<div><div class="card"><h2>2 · Changer l’état des sacs</h2><div class="cbody"><p class="hint">Exemples : HUMIDE → UTILISABLE après séchage ; DECHIRE → A_REPARER ; REPARE → UTILISABLE après contrôle.</p><label>Emplacement</label><select id="jv_tloc">'+locOpts()+'</select><div class="row"><div><label>État actuel</label><select id="jv_from">'+stateOpts()+'</select></div><div><label>Nouvel état</label><select id="jv_to">'+stateOpts()+'</select></div></div><div class="row"><div><label>Quantité</label><input id="jv_tqty" type="number" min="1"></div><div><label>Bon / fiche</label><input id="jv_tref"></div></div><label>Motif</label><input id="jv_tnote"><div class="actions"><button class="btn" onclick="RCNJuteV2UI.transition()">Enregistrer le contrôle</button></div></div></div>'+
 '<div class="card" style="margin-top:16px"><h2>Paramètres campagne</h2><div class="cbody"><div class="row"><div><label>Sacs par balle (standard)</label><input id="jv_bpb" type="number" value="'+n(set.bags_per_bale)+'" readonly></div><div><label>Seuil d’alerte</label><input id="jv_threshold" type="number" value="'+n(set.alert_threshold)+'"></div></div><div class="row"><div><label>Poids moyen par sac (kg)</label><input id="jv_avg" type="number" value="'+n(set.average_fill_kg)+'"></div><div><label>Référence initiale</label><input id="jv_initial" type="number" value="'+n(set.initial_reference)+'"></div></div><button class="btn ghost sm" onclick="RCNJuteV2UI.settings()">Mettre à jour</button></div></div></div></div>'+
 '<div class="card" style="margin-top:18px"><h2>Balance et ancienneté réelle par fournisseur <span class="badge b-ok">FIFO</span></h2><div class="cbody" style="padding:0"><div class="tablewrap"><table><thead><tr><th>Fournisseur</th><th>Remis</th><th>Retournés</th><th>Dus</th><th>Taux retour</th><th>+90 jours</th></tr></thead><tbody>'+supplierRows+'</tbody></table></div></div></div>'+
 '<div class="grid2" style="margin-top:18px"><div class="card"><h2>Réceptions partielles ouvertes</h2><div class="cbody" style="padding:0"><div class="tablewrap"><table><thead><tr><th>Document</th><th>Opération</th><th>Reste</th><th></th></tr></thead><tbody>'+(partialP+partialT+partialR||'<tr><td colspan="4" class="empty">Aucun solde ouvert.</td></tr>')+'</tbody></table></div></div></div><div class="card"><h2>Coût sacherie connu</h2><div class="cbody"><div class="metrics"><div class="metric"><small>Sacs achetés</small><b>'+money(costPurchase)+'</b></div><div class="metric"><small>Réparations</small><b>'+money(costRepair)+'</b></div></div><p class="hint">Le coût par tonne deviendra officiel lorsque les coûts de rebagging et le volume de campagne seront renseignés.</p></div></div></div>'+
 (supplierCode?supplierProfile(supplierCode):'')+'</section>';
 var head=root.querySelector('.pagehead');if(head)head.insertAdjacentHTML('afterend',html);else root.insertAdjacentHTML('afterbegin',html);enhanceLegacy(root);
}
function enhanceLegacy(root){Array.prototype.forEach.call(root.querySelectorAll('.card'),function(card){var h=card.querySelector('h2');if(!h||h.textContent.indexOf('Consommation rebagging')<0||card.querySelector('#jr_cost'))return;var btn=card.querySelector('button');if(btn)btn.insertAdjacentHTML('beforebegin','<label>Coût de rebagging par sac (FCFA)</label><input id="jr_cost" type="number" min="0" value="150"><p class="hint">Coût total calculé automatiquement et rattaché à la réception, au lot ou à la BIN.</p>');});}
function supplierProfile(code){var p=g.RCNJuteV2.profile(code),moves=g.RCNJuteV2.supplierMovements(code),f=(g.RCN.referentials().fournisseurs||[]).filter(function(x){return x.lba===code;})[0]||{};var rows=moves.map(function(x){return '<tr><td>'+new Date(x.movement_at).toLocaleDateString('fr-FR')+'</td><td>'+E(x.movement_type)+'</td><td>'+n(x.qty)+'</td><td>'+E(x.reference)+'</td><td>'+E(x.reception_id||'—')+'</td></tr>';}).join('')||'<tr><td colspan="5" class="empty">Aucun mouvement.</td></tr>';return '<div class="card" style="margin-top:18px;border:2px solid var(--emerald)"><h2>Fiche fournisseur · '+E(f.nom||code)+' <button class="btn ghost sm" onclick="location.hash=\'#sacscontrole\'">Fermer</button></h2><div class="cbody"><div class="metrics"><div class="metric"><small>Sacs dus</small><b>'+n(p&&p.balance)+'</b></div><div class="metric"><small>Taux de retour</small><b>'+n(p&&p.return_rate).toFixed(1)+' %</b></div><div class="metric"><small>Plus de 90 jours</small><b>'+n(p&&p.bucket_90_plus)+'</b></div></div><div class="tablewrap"><table><thead><tr><th>Date</th><th>Mouvement</th><th>Quantité</th><th>Référence</th><th>Réception</th></tr></thead><tbody>'+rows+'</tbody></table></div></div></div>';}
var API={
 pickReception:function(){var id=v('jv_rec'),r=g.RCNJuteV2.unsynced().filter(function(x){return x.id===id;})[0];if(!r)return;var total=n(r.dechargement&&r.dechargement.sacs),b=Math.floor(total/500),loose=total%500;document.getElementById('jv_total').value=total;document.getElementById('jv_bales').value=b;document.getElementById('jv_loose').value=loose;document.getElementById('jv_ref').value=(r.dechargement&&r.dechargement.bordereau)||r.id;var loc=document.getElementById('jv_loc');if(loc)loc.value=r.warehouse||r.site||loc.value;},
 reconcile:function(){var id=v('jv_rec'),r=g.RCNJuteV2.unsynced().filter(function(x){return x.id===id;})[0];if(!r){toast('Choisissez une réception.',true);return;}var file=document.getElementById('jv_proof').files[0];g.RCNJuteV2.uploadProof(file).then(function(path){return g.RCNJuteV2.reconcile({receptionId:id,supplierCode:r.lba,location:v('jv_loc'),campaign:r.campaign||'2026',total:v('jv_total'),company:v('jv_company'),supplier:v('jv_supplier'),unknown:v('jv_unknown'),usable:v('jv_usable'),humid:v('jv_humid'),torn:v('jv_torn'),repaired:v('jv_repaired'),other:v('jv_other'),bales:v('jv_bales'),loose:v('jv_loose'),reference:v('jv_ref'),note:v('jv_note'),proof:path});}).then(function(){toast('Rapprochement validé. Balance et stock mis à jour.');setTimeout(render,50);}).catch(function(e){toast(e.message,true);});},
 transition:function(){g.RCNJuteV2.transition({location:v('jv_tloc'),from:v('jv_from'),to:v('jv_to'),qty:v('jv_tqty'),reference:v('jv_tref'),note:v('jv_tnote')}).then(function(){toast('État des sacs mis à jour.');}).catch(function(e){toast(e.message,true);});},
 settings:function(){g.RCNJuteV2.updateSettings({bagsPerBale:v('jv_bpb'),threshold:v('jv_threshold'),avgKg:v('jv_avg'),initialReference:v('jv_initial')}).then(function(){toast('Paramètres mis à jour.');}).catch(function(e){toast(e.message,true);});},
 receivePartial:function(type,id,max){var q=prompt('Quantité reçue maintenant',max);if(q===null)return;var doc=prompt('Référence du bordereau de réception');if(!doc)return;var outcome=type==='ACHAT'?(prompt('Qualité : CONFORME, RESERVE ou REFUSE','CONFORME')||'CONFORME'):(prompt('Motif si écart','CONFORME')||'CONFORME');g.RCNJuteV2.partial(type,{id:id,qty:q,outcome:outcome,document:doc}).then(function(){toast('Réception partielle enregistrée.');}).catch(function(e){toast(e.message,true);});},
 receiveRepair:function(id,max){var ok=prompt('Sacs réparés reçus',max);if(ok===null)return;var bad=prompt('Sacs irréparables reçus','0');var doc=prompt('Référence du bordereau de retour');if(!doc)return;g.RCNJuteV2.repairPartial({id:id,repaired:ok,irreparable:bad,document:doc}).then(function(){toast('Retour de réparation enregistré.');}).catch(function(e){toast(e.message,true);});}
};
g.RCNJuteV2UI=API;
var timer;function schedule(){clearTimeout(timer);timer=setTimeout(render,80);}window.addEventListener('hashchange',schedule);new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true});schedule();
})(window);
