/* RCN TRACE — Registre central transactionnel des sacs de jute. */
(function(global){"use strict";
var URL="https://jmbdgpdthzpszfnddwzi.supabase.co",KEY="sb_publishable_Gu5j0VV4ymP-I9t3JriQXg_VlTJqV2d",sb=null,data=null,loading=null;
function c(){if(!sb&&global.supabase)sb=global.supabase.createClient(URL,KEY);return sb;}
var idSeq=0;
function id(p){idSeq=(idSeq+1)%46655;return p+"-"+new Date().getFullYear()+"-"+Date.now().toString(36).toUpperCase()+"-"+idSeq.toString(36).toUpperCase();}
function now(){return new Date().toISOString();}
function n(x){return Number(x||0);}
function load(){if(loading)return loading;var q=c();if(!q){data=data||{locations:[],movements:[],balances:[],stock:[],aging:[],losses:[],transfers:[],inventories:[],purchases:[],repairs:[]};return Promise.resolve(data);}/* hors connexion : structure vide plutôt que « Chargement » infini */loading=Promise.all([
 q.from("rcn_jute_locations").select("*").order("code"),
 q.from("rcn_jute_movements").select("*").order("movement_at",{ascending:false}).limit(1000),
 q.from("rcn_jute_v_supplier_balance").select("*"),
 q.from("rcn_jute_v_stock").select("*"),
 q.from("rcn_jute_v_aging").select("*"),
 q.from("rcn_jute_loss_requests").select("*").order("submitted_at",{ascending:false}),
 q.from("rcn_jute_transfers").select("*").order("created_at",{ascending:false}),
 q.from("rcn_jute_inventories").select("*").order("counted_at",{ascending:false}),
 q.from("rcn_jute_purchases").select("*").order("created_at",{ascending:false}),
 q.from("rcn_jute_repairs").select("*").order("sent_at",{ascending:false})
]).then(function(x){x.forEach(function(r){if(r.error)throw r.error;});data={locations:x[0].data||[],movements:x[1].data||[],balances:x[2].data||[],stock:x[3].data||[],aging:x[4].data||[],losses:x[5].data||[],transfers:x[6].data||[],inventories:x[7].data||[],purchases:x[8].data||[],repairs:x[9].data||[]};if(global.RCNTRACE_RERENDER)global.RCNTRACE_RERENDER();return data;}).catch(function(e){console.warn("Sacs jute indisponibles",e);data=data||{locations:[],movements:[],balances:[],stock:[],aging:[],losses:[],transfers:[],inventories:[],purchases:[],repairs:[]};return data;}).then(function(x){loading=null;return x;});return loading;}
function ensure(){return data?Promise.resolve(data):load();}
function reload(){data=null;return load();}
function rows(k){return data?(data[k]||[]):null;}
function addMovement(d){var row={id:id("JUT"),event_key:d.eventKey||id("EVT"),movement_type:d.type,ledger:d.ledger,supplier_code:d.supplierCode||null,qty:n(d.qty),from_location:d.fromLocation||null,to_location:d.toLocation||null,from_state:d.fromState||null,to_state:d.toState||null,reception_id:d.receptionId||null,lot_id:d.lotId||null,bin_id:d.binId||null,source_type:d.sourceType||null,source_id:d.sourceId||null,reference:d.reference,note:d.note||null,proof_url:d.proof||null,movement_at:d.at||now()};return c().from("rcn_jute_movements").insert(row).then(function(r){if(r.error)throw r.error;return reload();});}
function addLocation(d){return c().from("rcn_jute_locations").upsert({code:d.code,site_code:d.site,warehouse_code:d.warehouse,nom:d.name,type:d.type||"STOCK",actif:true},{onConflict:"code"}).then(function(r){if(r.error)throw r.error;return reload();});}
function setupLocations(){if(!c())return Promise.resolve(null);/* hors connexion / supabase absent : pas de crash */var rows=(global.RCN&&global.RCN.ENTREPOTS||[]).map(function(x){return {code:x.code,site_code:x.location||x.code,warehouse_code:x.code,nom:"Stock sacs · "+x.nom,type:"STOCK",actif:true};});rows.push({code:"JUTE-TRANSIT",site_code:"GLOBAL",warehouse_code:"TRANSIT",nom:"Sacs en transit",type:"TRANSIT",actif:true},{code:"JUTE-REPARATION",site_code:"GLOBAL",warehouse_code:"REPARATION",nom:"Sacs chez les réparateurs",type:"REPARATION",actif:true});return c().from("rcn_jute_locations").upsert(rows,{onConflict:"code"}).then(function(r){if(r.error)throw r.error;return reload();});}
function recordReception(rec){var d=rec&&rec.dechargement||{},total=n(d.sacs),loc=rec.warehouse||rec.site;if(!rec||!total||!loc)return Promise.reject(new Error("Réception, sacs et entrepôt requis."));
 var map=[["UTILISABLE",n(d.sacsBon)],["HUMIDE",n(d.sacsHumid)],["DECHIRE",n(d.sacsDechire)],["REPARE",n(d.sacsRecond)]],rows=[{id:id("JUT"),event_key:"REC:"+rec.id+":RETURN",movement_type:"RETOUR",ledger:"FOURNISSEUR",supplier_code:rec.lba,qty:total,reception_id:rec.id,source_type:"RECEPTION",source_id:rec.id,reference:rec.dechargement.bordereau||rec.id,note:"Retour automatique au déchargement",movement_at:d.at||now()}];
 map.forEach(function(x){if(x[1]>0)rows.push({id:id("JUT"),event_key:"REC:"+rec.id+":CLASS:"+x[0],movement_type:"CLASSEMENT",ledger:"INTERNE",qty:x[1],to_location:loc,to_state:x[0],reception_id:rec.id,source_type:"RECEPTION",source_id:rec.id,reference:rec.dechargement.bordereau||rec.id,note:"Classement automatique au déchargement",movement_at:d.at||now()});});
 return c().from("rcn_jute_movements").upsert(rows,{onConflict:"event_key",ignoreDuplicates:true}).then(function(r){if(r.error)throw r.error;return reload();});
}
function createTransfer(d){var tid=id("JTR");return c().from("rcn_jute_transfers").insert({id:tid,from_location:d.from,to_location:d.to,state:d.state,qty_sent:n(d.qty),vehicle:d.vehicle||null,driver:d.driver||null,document_ref:d.ref,proof_url:d.proof||null,statut:"PREPARE"}).then(function(r){if(r.error)throw r.error;return reload().then(function(){return tid;});});}
function shipTransfer(tid){var t=(data.transfers||[]).filter(function(x){return x.id===tid;})[0];if(!t)return Promise.reject(new Error("Transfert introuvable."));var mv={id:id("JUT"),event_key:"TRF:"+tid+":SHIP",movement_type:"TRANSFERT",ledger:"INTERNE",qty:t.qty_sent,from_location:t.from_location,to_location:"JUTE-TRANSIT",from_state:t.state,to_state:"EN_TRANSIT",source_type:"TRANSFERT",source_id:tid,reference:t.document_ref,note:"Expédition sacs",movement_at:now()};return c().from("rcn_jute_movements").insert(mv).then(function(r){if(r.error)throw r.error;return c().from("rcn_jute_transfers").update({statut:"EXPEDIE",sent_at:now()}).eq("id",tid);}).then(function(r){if(r.error)throw r.error;return reload();});}
function receiveTransfer(tid,qty,motif){var t=(data.transfers||[]).filter(function(x){return x.id===tid;})[0],q=n(qty);if(!t)return Promise.reject(new Error("Transfert introuvable."));if(q>n(t.qty_sent))return Promise.reject(new Error("Reçu supérieur à l’envoyé."));var mv={id:id("JUT"),event_key:"TRF:"+tid+":RECEIVE",movement_type:"TRANSFERT",ledger:"INTERNE",qty:q,from_location:"JUTE-TRANSIT",to_location:t.to_location,from_state:"EN_TRANSIT",to_state:t.state,source_type:"TRANSFERT",source_id:tid,reference:t.document_ref,note:"Réception sacs",movement_at:now()},gap=n(t.qty_sent)-q;return c().from("rcn_jute_movements").insert(mv).then(function(r){if(r.error)throw r.error;return c().from("rcn_jute_transfers").update({qty_received:q,ecart:gap,motif_ecart:motif||null,statut:gap?"ECART":"CLOS",received_at:now()}).eq("id",tid);}).then(function(r){if(r.error)throw r.error;return reload();});}
function submitLoss(d){return c().from("rcn_jute_loss_requests").insert({id:id("JLS"),supplier_code:d.supplierCode||null,location_code:d.location||null,state:d.state||null,qty:n(d.qty),ledger:d.ledger,motif:d.reason,proof_url:d.proof||null,statut:"SOUMIS"}).then(function(r){if(r.error)throw r.error;return reload();});}
function decideLoss(lid,ok,comment){var x=(data.losses||[]).filter(function(a){return a.id===lid;})[0];if(!x)return Promise.reject(new Error("Demande introuvable."));return c().from("rcn_jute_loss_requests").update({statut:ok?"APPROUVE":"REFUSE",commentaire_decision:comment||null,decided_at:now()}).eq("id",lid).then(function(r){if(r.error)throw r.error;if(!ok)return reload();return addMovement({eventKey:"LOSS:"+lid,type:x.ledger==="FOURNISSEUR"?"PERTE_APPROUVEE":"REFORME",ledger:x.ledger,supplierCode:x.supplier_code,qty:x.qty,fromLocation:x.location_code,fromState:x.state,sourceType:"PERTE",sourceId:lid,reference:lid,note:x.motif});});}
function createInventory(d){var theoretical=(data.stock||[]).filter(function(x){return x.location_code===d.location&&x.state===d.state;})[0];return c().from("rcn_jute_inventories").insert({id:id("INV"),location_code:d.location,state:d.state,theoretical_qty:n(theoretical&&theoretical.qty),counted_qty:n(d.counted),motif:d.reason||null,proof_url:d.proof||null,statut:"SOUMIS"}).then(function(r){if(r.error)throw r.error;return reload();});}
function decideInventory(iid,ok){var x=(data.inventories||[]).filter(function(a){return a.id===iid;})[0];if(!x)return Promise.reject(new Error("Inventaire introuvable."));return c().from("rcn_jute_inventories").update({statut:ok?"APPROUVE":"REFUSE",approved_at:now()}).eq("id",iid).then(function(r){if(r.error)throw r.error;if(!ok||!n(x.difference_qty))return reload();var diff=n(x.difference_qty);return addMovement({eventKey:"INV:"+iid,type:"AJUSTEMENT_INVENTAIRE",ledger:"INTERNE",qty:Math.abs(diff),fromLocation:diff<0?x.location_code:null,toLocation:diff>0?x.location_code:null,fromState:diff<0?x.state:null,toState:diff>0?x.state:null,sourceType:"INVENTAIRE",sourceId:iid,reference:iid,note:x.motif||"Ajustement inventaire approuvé"});});}
function createPurchase(d){var pid=id("JPO");return c().from("rcn_jute_purchases").insert({id:pid,vendor:d.vendor,po_ref:d.po,qty_ordered:n(d.ordered),unit_price:n(d.price),lot_fabrication:d.batch||null,destination_location:d.location,proof_url:d.proof||null,statut:"COMMANDE"}).then(function(r){if(r.error)throw r.error;return reload().then(function(){return pid;});});}
function receivePurchase(pid,qty,quality){var p=(data.purchases||[]).filter(function(x){return x.id===pid;})[0],q=n(qty);if(!p)return Promise.reject(new Error("Commande introuvable."));if(q>n(p.qty_ordered))return Promise.reject(new Error("Réception supérieure à la commande."));return c().from("rcn_jute_purchases").update({qty_received:q,quality_status:quality,received_at:now(),statut:quality==="REFUSE"?"REFUSE":(q<n(p.qty_ordered)?"PARTIEL":"RECU")}).eq("id",pid).then(function(r){if(r.error)throw r.error;if(quality==="REFUSE")return reload();return addMovement({eventKey:"PURCHASE:"+pid,type:"ACHAT",ledger:"INTERNE",qty:q,toLocation:p.destination_location,toState:"UTILISABLE",sourceType:"ACHAT",sourceId:pid,reference:p.po_ref,note:"Réception sacs neufs"});});}
function createRepair(d){var rid=id("JRP");return c().from("rcn_jute_repairs").insert({id:rid,from_location:d.from,return_location:d.returnTo,repairer:d.repairer,qty_sent:n(d.qty),cost:n(d.cost),document_ref:d.ref,proof_url:d.proof||null,statut:"ENVOYE"}).then(function(r){if(r.error)throw r.error;return addMovement({eventKey:"REPAIR:"+rid+":SEND",type:"REPARATION_SORTIE",ledger:"INTERNE",qty:d.qty,fromLocation:d.from,toLocation:"JUTE-REPARATION",fromState:"A_REPARER",toState:"A_REPARER",sourceType:"REPARATION",sourceId:rid,reference:d.ref,note:"Envoi chez "+d.repairer});}).then(function(){return rid;});}
function receiveRepair(rid,repaired,irreparable){var x=(data.repairs||[]).filter(function(a){return a.id===rid;})[0],ok=n(repaired),bad=n(irreparable);if(!x)return Promise.reject(new Error("Réparation introuvable."));if(ok+bad<=0)return Promise.reject(new Error("Indiquez au moins un sac réparé ou irréparable."));if(ok+bad>n(x.qty_sent))return Promise.reject(new Error("Quantités reçues supérieures aux sacs envoyés."));var rows=[];if(ok)rows.push({id:id("JUT"),event_key:"REPAIR:"+rid+":OK",movement_type:"REPARATION_RETOUR",ledger:"INTERNE",qty:ok,from_location:"JUTE-REPARATION",to_location:x.return_location,from_state:"A_REPARER",to_state:"REPARE",source_type:"REPARATION",source_id:rid,reference:x.document_ref,note:"Sacs réparés"});if(bad)rows.push({id:id("JUT"),event_key:"REPAIR:"+rid+":BAD",movement_type:"REFORME",ledger:"INTERNE",qty:bad,from_location:"JUTE-REPARATION",to_location:x.return_location,from_state:"A_REPARER",to_state:"REFORME",source_type:"REPARATION",source_id:rid,reference:x.document_ref,note:"Sacs irréparables"});return c().from("rcn_jute_movements").insert(rows).then(function(r){if(r.error)throw r.error;return c().from("rcn_jute_repairs").update({qty_repaired:ok,qty_irreparable:bad,returned_at:now(),statut:ok+bad===n(x.qty_sent)?"CLOS":"ECART"}).eq("id",rid);}).then(function(r){if(r.error)throw r.error;return reload();});}
function rebag(d){return addMovement({eventKey:"REBAG:"+d.reference,type:"REBAGING",ledger:"INTERNE",qty:d.qty,fromLocation:d.location,fromState:"UTILISABLE",receptionId:d.receptionId,lotId:d.lotId,binId:d.binId,sourceType:"REBAGING",sourceId:d.reference,reference:d.reference,note:d.note});}
function stockAt(loc,state){var x=(data&&data.stock||[]).filter(function(a){return a.location_code===loc&&a.state===state;})[0];return n(x&&x.qty);}
function stats(){var bal=data&&data.balances||[],st=data&&data.stock||[];return {debt:bal.reduce(function(t,x){return t+n(x.balance);},0),internal:st.reduce(function(t,x){return t+n(x.qty);},0),unclassified:st.filter(function(x){return x.state==="A_CLASSER";}).reduce(function(t,x){return t+n(x.qty);},0),pendingLoss:(data&&data.losses||[]).filter(function(x){return x.statut==="SOUMIS";}).length,transferGap:(data&&data.transfers||[]).filter(function(x){return x.statut==="ECART";}).length};}
global.RCNJuteControl={load:load,ensure:ensure,data:function(){return data;},rows:rows,addMovement:addMovement,addLocation:addLocation,setupLocations:setupLocations,recordReception:recordReception,createTransfer:createTransfer,shipTransfer:shipTransfer,receiveTransfer:receiveTransfer,submitLoss:submitLoss,decideLoss:decideLoss,createInventory:createInventory,decideInventory:decideInventory,createPurchase:createPurchase,receivePurchase:receivePurchase,createRepair:createRepair,receiveRepair:receiveRepair,rebag:rebag,stockAt:stockAt,stats:stats};
})(window);
